// Generated by dts-bundle-generator v9.5.1

declare const AbruptCompletion: {
	is(value: unknown): value is AbruptCompletion;
	assert(value: unknown): asserts value is AbruptCompletion;
};
declare const BindingNameNamespace: unique symbol;
declare const ControlFlowCompletion: {
	is(value: unknown): value is ControlFlowCompletion;
	assert(value: unknown): asserts value is ControlFlowCompletion;
	handleRuntime(value: unknown): void;
};
declare const StaticJsRealm$1: StaticJsRealm$1;
declare const StaticJsRealm$2: StaticJsRealm$1;
declare const WellKnownErrorNames: readonly [
	"AggregateError",
	"Error",
	"EvalError",
	"RangeError",
	"ReferenceError",
	"SyntaxError",
	"TypeError",
	"URIError"
];
declare const symbolInspect: unique symbol;
declare function BreakCompletion(target?: string | null, value?: StaticJsValue | null): BreakCompletion;
declare function ContinueCompletion(target?: string | null, value?: StaticJsValue | null): ContinueCompletion;
declare function NormalCompletion(value: CompletionValue): NormalCompletion;
declare function ReturnCompletion(value: StaticJsValue): ReturnCompletion;
declare function ThrowCompletion(value: StaticJsValue): ThrowCompletion;
declare namespace BreakCompletion {
	var is: (value: unknown) => value is BreakCompletion;
	var assert: (value: unknown) => asserts value is BreakCompletion;
}
declare namespace ContinueCompletion {
	var is: (value: unknown) => value is ContinueCompletion;
	var assert: (value: unknown) => asserts value is ContinueCompletion;
	var isContinueForLabel: (e: unknown, label: string | null) => e is ContinueCompletion;
}
declare namespace NormalCompletion {
	var is: (value: unknown) => value is NormalCompletion;
	var demand: (value: unknown) => asserts value is NormalCompletion;
}
declare namespace ReturnCompletion {
	var is: (value: unknown) => value is ReturnCompletion;
	var assert: (value: unknown) => asserts value is ReturnCompletion;
}
declare namespace ThrowCompletion {
	var create: (type: WellKnownErrorName, message: string, realm?: StaticJsRealm) => EvaluationGenerator<ThrowCompletion>;
	var is: (value: unknown) => value is ThrowCompletion;
	var assert: (value: unknown) => asserts value is ThrowCompletion;
	var handleRuntime: (value: unknown) => void;
	var toRuntime: (completion: ThrowCompletion) => never;
}
export declare class StaticJsConcurrentEvaluationError extends Error {
	constructor(message?: string);
	[symbolInspect](): string;
}
export declare class StaticJsEngineError extends Error {
	constructor(message: string);
	[symbolInspect](): string;
}
export declare class StaticJsRuntimeError extends Error {
	private readonly _thrown;
	private readonly _prefix;
	private _message;
	constructor(_thrown: StaticJsValue, _prefix?: string);
	get thrown(): StaticJsValue;
	toNative(): Record<string, unknown>;
	[symbolInspect](): string;
	get [Symbol.toStringTag](): string;
	toJSON(): Record<string, unknown>;
}
export declare class StaticJsSynchronousTaskIncompleteError extends Error {
	constructor(message?: string);
	[symbolInspect](): string;
}
export declare class StaticJsSyntaxError extends Error {
	private _loc;
	constructor(message: string, _loc: SyntaxErrorLocation | null);
	get loc(): SyntaxErrorLocation | null;
	[symbolInspect](): string;
}
export declare class StaticJsTaskAbortedError extends StaticJsTaskError {
	/**
	 * Creates a new StaticJsTaskAbortedError.
	 * @param message The error message.
	 */
	constructor(message?: string);
}
export declare class StaticJsTaskCompletedError extends StaticJsTaskError {
	/**
	 * Creates a new StaticJsTaskCompletedError.
	 * @param message The error message.
	 */
	constructor(message?: string);
}
export declare class StaticJsTaskError extends Error {
	/**
	 * Creates a new StaticJsTaskError.
	 * @param message The error message.
	 */
	constructor(message?: string);
	[symbolInspect](): string;
}
export declare class StaticJsUnhandledRejectionError extends StaticJsRuntimeError {
	constructor(thrown: StaticJsValue);
}
export declare class StubEvaluationGenerator<T> extends Iterator<EvaluatorCommandBase, T, CompletionValue> implements EvaluationGenerator<T> {
	private _returnValue;
	[Symbol.iterator](): this;
	constructor(_returnValue: T);
	next(): IteratorResult<EvaluatorCommandBase, T>;
	return(): IteratorResult<EvaluatorCommandBase, T>;
	throw(): IteratorResult<EvaluatorCommandBase, T>;
}
export declare const AllHostAccessStubTypes: readonly [
	"array",
	"error"
];
export declare const HostAccessOptionKeys: readonly (keyof HostAccessOptions)[];
export declare const MAX_ARRAY_LENGTH_INCLUSIVE: number;
export declare const StaticJsProxyHandlerKeys: string[];
export declare const realmDefaultHooks: {
	math: MathHooks;
};
export declare enum StaticJsTypeCode {
	IsScalarFlag = 64,
	IsObjectFlag = 128,
	IsCallableFlag = 256,
	Null = 64,
	String = 65,
	Boolean = 66,
	Number = 67,
	Symbol = 68,
	Undefined = 69,
	PlainObject = 134,
	Array = 135,
	Function = 392,
	Error = 137,
	Promise = 138,
	Iterator = 139,
	AsyncIterator = 140,
	Set = 141,
	Map = 142,
	Generator = 143,
	AsyncGenerator = 144,
	Proxy = 145,
	ProxyCallable = 402
}
export declare function EvaluationGenerator<T>(maybe: MaybeEvaluationGenerator<T>): EvaluationGenerator<T>;
export declare function createTimeBoundTaskRunner({ maxRunTime, maxTaskTime, }?: TimeBoundTaskRunnerOptions): StaticJsTaskRunner;
export declare function createTimeSharingTaskRunner({ operationsPerIteration, yieldTime, maxRunTime, maxTaskTime, }?: TimeSharingTaskRunnerOptions): StaticJsTaskRunner;
/**
 * Evaluates a string as a javascript program, and returns the result.
 * @param expression The string containing javascript code to evaluate.
 * @param opts The options for the evaluation.
 * @param callback An optional callback to receive and process the results of the expression.  This can be used to differentiate promises returned by the expression from the promise returned by this function, and to handle errors without throwing them.
 * @returns The native javascript result of evaluating the code.
 * @public
 */
export declare function evaluateExpression(expression: string, opts?: EvaluationOptions, callback?: (value: unknown, error?: unknown) => Promise<unknown> | void): Promise<unknown>;
/**
 * Evaluates a string as a javascript program, and synchronously returns the result.
 * @param expression The string containing javascript code to evaluate.
 * @param opts The options for the evaluation.
 * @returns The native javascript result of evaluating the code.
 * @public
 */
export declare function evaluateExpressionSync(expression: string, opts?: EvaluationOptions): unknown;
/**
 * Evaluates a string as a javascript program, and returns the result.
 * @param code - The string containing javascript code to evaluate.
 * @param opts - The options for the evaluation.
 * @returns The native javascript result of evaluating the code.
 * @public
 */
export declare function evaluateModule(code: string, opts?: EvaluationOptions): Promise<StaticJsModule>;
/**
 * Evaluates a string as a javascript program, and returns the result.
 * @param script The string containing javascript code to evaluate.
 * @param opts The options for the evaluation.
 * @param callback An optional callback to receive and process the results of the expression.  This can be used to differentiate promises returned by the expression from the promise returned by this function, and to handle errors without throwing them.
 * @returns The native javascript result of evaluating the code.
 * @public
 */
export declare function evaluateScript(script: string, opts?: EvaluateScriptOptions, callback?: (value: unknown, error?: unknown) => Promise<unknown> | void): Promise<unknown>;
export declare function evaluateScriptSync(script: string, opts?: EvaluationOptions): unknown;
export declare function isEvaluationGenerator(value: unknown): value is EvaluationGenerator<unknown>;
export declare function isStaticJsAccessorPropertyDescriptor(value: StaticJsPropertyDescriptor): value is StaticJsAccessorPropertyDescriptor;
export declare function isStaticJsAccessorPropertyDescriptor(value: unknown): value is StaticJsPropertyDescriptorRecord & (Required<Pick<StaticJsPropertyDescriptorRecord, "get">> | Required<Pick<StaticJsPropertyDescriptorRecord, "set">>);
export declare function isStaticJsArray(value: unknown): value is StaticJsArray;
export declare function isStaticJsAsyncGenerator(value: unknown): value is StaticJsAsyncGenerator;
export declare function isStaticJsBoolean(value: unknown): value is StaticJsBoolean;
export declare function isStaticJsBoundFunction(value: unknown): value is StaticJsBoundFunction;
export declare function isStaticJsCallable(value: unknown): value is StaticJsCallable;
export declare function isStaticJsDataPropertyDescriptor(value: StaticJsPropertyDescriptor): value is StaticJsDataPropertyDescriptor;
export declare function isStaticJsDataPropertyDescriptor(value: unknown): value is StaticJsPropertyDescriptorRecord & (Required<Pick<StaticJsPropertyDescriptorRecord, "value">> | Required<Pick<StaticJsPropertyDescriptorRecord, "writable">>);
export declare function isStaticJsError(value: StaticJsObject): value is StaticJsError;
export declare function isStaticJsFunction(value: unknown): value is StaticJsFunction;
export declare function isStaticJsGenerator(value: unknown): value is StaticJsGenerator;
export declare function isStaticJsGenericPropertyDescriptor(value: unknown): value is Pick<StaticJsPropertyDescriptorRecord, "configurable" | "enumerable"> & {
	get: never;
	set: never;
	value: never;
	writable: never;
};
export declare function isStaticJsIterator(value: unknown): value is StaticJsIterator;
export declare function isStaticJsMap(value: unknown): value is StaticJsMap;
export declare function isStaticJsModule(x: unknown): x is StaticJsModule;
export declare function isStaticJsNull(value: unknown): value is StaticJsNull;
export declare function isStaticJsNumber(value: unknown): value is StaticJsNumber;
export declare function isStaticJsObject(value: unknown): value is StaticJsObject;
export declare function isStaticJsPlainObject(value: unknown): value is StaticJsPlainObject;
export declare function isStaticJsPrivateElement(value: unknown): value is StaticJsPrivateElement;
export declare function isStaticJsPrivateName(value: unknown): value is StaticJsPrivateName;
export declare function isStaticJsPromise(value: unknown): value is StaticJsPromise;
export declare function isStaticJsPropertyKey(value: unknown): value is StaticJsPropertyKey;
export declare function isStaticJsProxy(value: unknown): value is StaticJsProxy;
export declare function isStaticJsRealm(value: unknown): value is StaticJsRealm;
export declare function isStaticJsScalar(value: unknown): value is StaticJsScalar;
export declare function isStaticJsSet(value: unknown): value is StaticJsSet;
export declare function isStaticJsString(value: unknown): value is StaticJsString;
export declare function isStaticJsSymbol(value: unknown): value is StaticJsSymbol;
export declare function isStaticJsUndefined(value: unknown): value is StaticJsUndefined;
export declare function isStaticJsValue(value: unknown): value is StaticJsValue;
export declare function propertyDescriptorToNative(descriptor: StaticJsPropertyDescriptor, realm: StaticJsRealm): PropertyDescriptor;
export declare function propertyDescriptorToStaticJsObject(descriptor: StaticJsPropertyDescriptorRecord | undefined, realm: StaticJsRealm): EvaluationGenerator<StaticJsPlainObject | StaticJsUndefined>;
export declare function propertyDescriptorToStaticJsObject(descriptor: StaticJsPropertyDescriptorRecord, realm: StaticJsRealm): EvaluationGenerator<StaticJsPlainObject>;
export declare function staticJsPrivateElementAccessor(key: StaticJsPrivateName, accessors: {
	get?: StaticJsFunction;
	set?: StaticJsFunction;
}): StaticJsPrivateElementAccessor;
export declare function staticJsPrivateElementField(key: StaticJsPrivateName, value: StaticJsValue): StaticJsPrivateElementField;
export declare function staticJsPrivateName(description: string): StaticJsPrivateName;
export declare function staticJsPropertyKeyToValue(key: StaticJsPropertyKey, realm: StaticJsRealm): StaticJsValue;
export declare function staticJsValueToPropertyKey(value: StaticJsValue): StaticJsPropertyKey;
export declare function toStaticJsPropertyKey(value: CompletionValue): StaticJsPropertyKey;
export declare function validateStaticJsPropertyDescriptorRecord(value: unknown): asserts value is StaticJsPropertyDescriptorRecord;
export declare namespace Completion {
	type Break = BreakCompletion;
	const Break: typeof BreakCompletion;
	type Continue = ContinueCompletion;
	const Continue: typeof ContinueCompletion;
	type Normal = NormalCompletion;
	const Normal: typeof NormalCompletion;
	type Return = ReturnCompletion;
	const Return: typeof ReturnCompletion;
	type Throw = ThrowCompletion;
	const Throw: typeof ThrowCompletion;
	type Abrupt = AbruptCompletion;
	const Abrupt: {
		is(value: unknown): value is AbruptCompletion;
		assert(value: unknown): asserts value is AbruptCompletion;
	};
	type ControlFlow = ControlFlowCompletion;
	const ControlFlow: {
		is(value: unknown): value is ControlFlowCompletion;
		assert(value: unknown): asserts value is ControlFlowCompletion;
		handleRuntime(value: unknown): void;
	};
	function is(value: unknown): value is Completion;
	function assert(value: unknown): asserts value is Completion;
	function value<T extends CompletionValue>(completion: T): T;
	function value(completion: CompletionValue): CompletionValue;
	function value(completion: Completion.Abrupt): StaticJsValue;
	function value(completion: Completion): CompletionValue;
	function updateEmpty(completion: Completion, value: CompletionValue): Completion;
	function unhandled(value: AbruptCompletion): never;
	function handleRuntime(value: unknown): void;
}
export interface EvaluateScriptOptions extends EvaluationOptions {
	/**
	 * Whether to allow top-level await in the script.
	 *
	 * If true, the result of evaluating the script will be a promise that resolves to the value of
	 * the last expression in the script, or undefined if there are no expressions.
	 *
	 * If false, top-level await will not be allowed, and a SyntaxError will be thrown if it is used.
	 *
	 * If "auto", the engine will return a promise only if top-level await is used in the script, and will
	 * return the value of the last expression directly if top-level await is not used.
	 */
	topLevelAwait?: boolean | "auto";
}
/**
 * Policy controlling how a host JavaScript object is exposed to a
 * StaticJsRealm sandbox via `StaticJsTypeFactory.toStaticJsValue`.
 *
 * Default behavior (no options, or all fields false) reproduces the
 * locked-down view: own enumerable properties only, read-only, no
 * prototype walk, sandbox's `Object.prototype`.
 */
export interface HostAccessOptions {
	/**
	 * Whether to stub well-known host types (e.g. Array, Function) with sandbox-local equivalents that have the same identity as the realm intrinsics, so instanceof and prototype checks work as expected.
	 * This defaults to true, as .toNative() on functions can appear non-functional without it.
	 *
	 * When turning this off, expect native arrays to be treated as plain objects with no array behavior, including lacking an iterator.  Usually, this should only be turned off
	 * if you intend to enable prototypePolicy.
	 *
	 * Possible values:
	 * - "array": Stub arrays into sandboxed arrays, invoking childPolicy for array items.
	 * - "error": Stub Errors into sandboxed Errors, with message and name properties but no stack traces.
	 *
	 * Note that all stubs are read-only, regardless of the writable/extensible options.  The exception is functions, which will still invoke, but will invoke childPolicy for return values.
	 * @default true
	 */
	stubWellKnownTypes?: boolean | HostAccessStubType[];
	/**
	 * Expose non-enumerable own properties (e.g. ES class methods).
	 *
	 * Note: This applies to enumerable non-well-known symbols as well.
	 *
	 * @default false
	 */
	includeNonEnumerable?: boolean;
	/**
	 * Expose well-known symbols (e.g. Symbol.iterator) as property keys on host objects.
	 * This defaults to true, to allow arrays and other items to iterate.  However, it typically
	 * will not engage for most builtins without prototypePolicy.
	 *
	 * @default true
	 */
	includeWellKnownSymbols?: boolean;
	/**
	 * Allow sandbox writes to mutate the host object.
	 * If true, the sandbox can modify data properties on the host.
	 * If false, the sandbox cannot modify data properties.
	 * If "transparent", the sandbox can modify data properties, but those modifications are not reflected back to the host (i.e. the wrapper stores its own copy of the data property value once it's written to).
	 * @default false
	 * */
	writable?: boolean | "transparent";
	/**
	 * Allow the sandbox to add properties to the host object.
	 * If true, the sandbox can add properties to the host object, and those properties are reflected back to the host.
	 * If false, the sandbox cannot add properties to the host object.
	 * If "transparent", the sandbox can add properties to the host object, but those properties are not reflected back to the host (i.e. the wrapper stores its own copy of the added property and value).
	 * @default false
	 */
	extensible?: boolean | "transparent";
	/**
	 * When a host method is invoked from the sandbox, pass the sandbox-side
	 * `this` (round-tripped to its backing host value) instead of the
	 * captured backing object.
	 * @default false
	 */
	useSandboxThis?: boolean;
	/**
	 * Opt out of substituting host builtin prototypes with the realm's
	 * intrinsic equivalents. Default false; host builtin prototypes are
	 * mapped to the matching sandbox intrinsic so host builtin identities
	 * are never reachable from inside the sandbox.
	 * @default false
	 */
	rawPrototypes?: boolean;
	/**
	 * Policy for the prototype of the host object.
	 *
	 * If "inherit", it will reuse the parent's resolved policy.
	 * If "default", the realm default policy is used.
	 * If false, the sandbox-visible [[Prototype]] is always the realm's default prototype for the type (Object.prototype for objects, Function.prototype for functions, etc.),
	 * regardless of the host object's actual prototype (including null).
	 * If a StaticJsValue, the returned value will be used as the sandbox-visible [[Prototype]] for the host object, and the host object's actual prototype will not be visible in the sandbox.
	 * If an object, the returned HostAccessOptions will be used for prototypes as well as own properties, and for their descendants, unless overridden by a closer ancestor.
	 * If a function, it will be invoked with each prototype object to determine the policy. Decide on a per-object basis.
	 * @default false
	 */
	prototypePolicy?: HostAccessChildOptions;
	/**
	 * Policy for objects reached transitively from this one (property
	 * values, function return values, prototype-chain entries that are
	 * themselves host objects).
	 *
	 * If "inherit", it will reuse the parent's resolved policy.
	 * If "default", the realm default policy is used.
	 * If false, the child is not exposed — it resolves to `undefined`.
	 * If an object, the returned HostAccessOptions will be used for that child object and its descendants, unless overridden by a closer ancestor.
	 * If a function, it will be invoked with the child host object to determine the policy. Decide on a per-object basis.
	 *
	 * childHostObj may be any non-primitive host value — plain object, host
	 * function, host class instance, host prototype.
	 *
	 * Not consulted for the root object itself.
	 * @default "default"
	 */
	childPolicy?: HostAccessChildOptions;
}
export interface IntrinsicSymbols {
	asyncIterator: StaticJsSymbol;
	hasInstance: StaticJsSymbol;
	isConcatSpreadable: StaticJsSymbol;
	iterator: StaticJsSymbol;
	match: StaticJsSymbol;
	matchAll: StaticJsSymbol;
	replace: StaticJsSymbol;
	search: StaticJsSymbol;
	species: StaticJsSymbol;
	split: StaticJsSymbol;
	toPrimitive: StaticJsSymbol;
	toStringTag: StaticJsSymbol;
	unscopables: StaticJsSymbol;
}
export interface IntrinsicsRecord {
	AggregateError: StaticJsFunction;
	["AggregateError.prototype"]: StaticJsObject;
	Array: StaticJsFunction;
	["Array.prototype"]: StaticJsObject;
	ArrayIteratorPrototype: StaticJsObject;
	AsyncFromSyncIteratorPrototype: StaticJsObject;
	AsyncFunction: StaticJsFunction;
	["AsyncFunction.prototype"]: StaticJsObject;
	AsyncGeneratorFunction: StaticJsFunction;
	["AsyncGeneratorFunction.prototype"]: StaticJsObject;
	AsyncGeneratorPrototype: StaticJsObject;
	AsyncIteratorPrototype: StaticJsObject;
	Boolean: StaticJsFunction;
	["Boolean.prototype"]: StaticJsObject;
	Error: StaticJsFunction;
	["Error.prototype"]: StaticJsObject;
	eval: StaticJsFunction;
	EvalError: StaticJsFunction;
	["EvalError.prototype"]: StaticJsObject;
	ForInIteratorPrototype: StaticJsObject;
	Function: StaticJsFunction;
	["Function.prototype"]: StaticJsCallable;
	GeneratorFunction: StaticJsFunction;
	["GeneratorFunction.prototype"]: StaticJsObject;
	GeneratorPrototype: StaticJsObject;
	isFinite: StaticJsFunction;
	isNaN: StaticJsFunction;
	Iterator: StaticJsFunction;
	["Iterator.prototype"]: StaticJsObject;
	IteratorHelperPrototype: StaticJsObject;
	Map: StaticJsFunction;
	["Map.prototype"]: StaticJsObject;
	MapIteratorPrototype: StaticJsObject;
	Math: StaticJsObject;
	Number: StaticJsFunction;
	["Number.prototype"]: StaticJsObject;
	Object: StaticJsFunction;
	["Object.prototype"]: StaticJsObject;
	parseFloat: StaticJsFunction;
	parseInt: StaticJsFunction;
	Promise: StaticJsFunction;
	["Promise.prototype"]: StaticJsObject;
	Proxy: StaticJsFunction;
	RangeError: StaticJsFunction;
	["RangeError.prototype"]: StaticJsObject;
	ReferenceError: StaticJsFunction;
	["ReferenceError.prototype"]: StaticJsObject;
	Reflect: StaticJsObject;
	Set: StaticJsFunction;
	["Set.prototype"]: StaticJsObject;
	SetIteratorPrototype: StaticJsObject;
	String: StaticJsFunction;
	["String.prototype"]: StaticJsObject;
	StringIteratorPrototype: StaticJsObject;
	Symbol: StaticJsFunction;
	["Symbol.prototype"]: StaticJsObject;
	["Symbol.asyncDispose"]: StaticJsSymbol;
	["Symbol.asyncIterator"]: StaticJsSymbol;
	["Symbol.dispose"]: StaticJsSymbol;
	["Symbol.hasInstance"]: StaticJsSymbol;
	["Symbol.isConcatSpreadable"]: StaticJsSymbol;
	["Symbol.iterator"]: StaticJsSymbol;
	["Symbol.match"]: StaticJsSymbol;
	["Symbol.matchAll"]: StaticJsSymbol;
	["Symbol.replace"]: StaticJsSymbol;
	["Symbol.search"]: StaticJsSymbol;
	["Symbol.species"]: StaticJsSymbol;
	["Symbol.split"]: StaticJsSymbol;
	["Symbol.toPrimitive"]: StaticJsSymbol;
	["Symbol.toStringTag"]: StaticJsSymbol;
	["Symbol.unscopables"]: StaticJsSymbol;
	SyntaxError: StaticJsFunction;
	["SyntaxError.prototype"]: StaticJsObject;
	ThrowTypeError: StaticJsFunction;
	TypeError: StaticJsFunction;
	["TypeError.prototype"]: StaticJsObject;
	URIError: StaticJsFunction;
	["URIError.prototype"]: StaticJsObject;
}
export interface RealmHooks {
	math: MathHooks;
}
export interface StaticJsAccessorPropertyDescriptor {
	configurable: boolean;
	enumerable: boolean;
	get: StaticJsCallable | undefined;
	set: StaticJsCallable | undefined;
}
export interface StaticJsArray extends StaticJsObject {
	readonly runtimeTypeOf: "array";
}
export interface StaticJsAsyncGenerator extends StaticJsObject {
	readonly runtimeTypeOf: "async-generator";
	nextSync(value?: StaticJsValue, opts?: StaticJsRunTaskOptions): StaticJsPromise;
	nextAsync(value?: StaticJsValue, opts?: StaticJsRunTaskOptions): Promise<StaticJsPromise>;
	nextEvaluator(value?: StaticJsValue): EvaluationGenerator<StaticJsPromise>;
	returnSync(value?: StaticJsValue, opts?: StaticJsRunTaskOptions): StaticJsPromise;
	returnAsync(value?: StaticJsValue, opts?: StaticJsRunTaskOptions): Promise<StaticJsPromise>;
	returnEvaluator(value?: StaticJsValue): EvaluationGenerator<StaticJsPromise>;
	throwSync(value: StaticJsValue, opts?: StaticJsRunTaskOptions): StaticJsPromise;
	throwAsync(value: StaticJsValue, opts?: StaticJsRunTaskOptions): Promise<StaticJsPromise>;
	throwEvaluator(value: StaticJsValue): EvaluationGenerator<StaticJsPromise>;
}
export interface StaticJsBoolean extends StaticJsPrimitive {
	readonly runtimeTypeOf: "boolean";
	value: boolean;
	negate(): StaticJsBoolean;
}
export interface StaticJsBoundFunction extends StaticJsFunction {
	boundTargetFunction: StaticJsFunction;
}
export interface StaticJsCallable extends StaticJsObject {
	get isConstructor(): boolean;
	callAsync(thisArg: StaticJsValue, args?: StaticJsValue[], opts?: StaticJsRunTaskOptions): Promise<StaticJsValue>;
	callSync(thisArg: StaticJsValue, args?: StaticJsValue[], opts?: StaticJsRunTaskOptions): StaticJsValue;
	callEvaluator(thisArg: StaticJsValue, args?: StaticJsValue[]): EvaluationGenerator<StaticJsValue>;
	constructAsync(args?: StaticJsValue[], newTarget?: StaticJsCallable, opts?: StaticJsRunTaskOptions): Promise<StaticJsObject>;
	constructSync(args?: StaticJsValue[], newTarget?: StaticJsCallable, opts?: StaticJsRunTaskOptions): StaticJsObject;
	constructEvaluator(args?: StaticJsValue[], newTarget?: StaticJsCallable): EvaluationGenerator<StaticJsObject>;
	toNative(opts?: StaticJsCallableToNativeOpts): unknown;
}
/**
 * Options for converting a callable to its native (host) function bridge via
 * {@link StaticJsCallable.toNative}.
 */
export interface StaticJsCallableToNativeOpts {
	/**
	 * Host access to apply to the `this` and arguments handed back to the
	 * function when the native bridge is invoked. This is passed verbatim as the
	 * `opts` argument of `StaticJsTypeFactory.toStaticJsValue` for each value, so
	 * a sandbox function passed into host code can keep an inherited access level
	 * on its callback boundary instead of collapsing to the realm defaults. When
	 * omitted, values use the realm's default `toStaticJsValue` behavior.
	 */
	access?: HostAccessArg;
}
export interface StaticJsDataPropertyDescriptor {
	configurable: boolean;
	enumerable: boolean;
	writable: boolean;
	value: StaticJsValue;
}
export interface StaticJsEnvironmentRecord {
	get outerEnv(): StaticJsEnvironmentRecord | null;
	inspectBindingsEvaluator(): EvaluationGenerator<Record<string, StaticJsValue | null>>;
	hasBindingEvaluator(name: string): EvaluationGenerator<boolean>;
	createMutableBindingEvaluator(name: string, deletable: boolean): EvaluationGenerator<void>;
	createImmutableBindingEvaluator(name: string, strict: boolean): EvaluationGenerator<void>;
	isInitializedEvaluator(name: string): EvaluationGenerator<boolean>;
	initializeBindingEvaluator(name: string, value: StaticJsValue): EvaluationGenerator<void>;
	setMutableBindingEvaluator(name: string, value: StaticJsValue, strict: boolean): EvaluationGenerator<void>;
	getBindingValueEvaluator(name: string, strict: boolean): EvaluationGenerator<StaticJsValue>;
	deleteBindingEvaluator(name: string): EvaluationGenerator<boolean>;
	hasThisBindingEvaluator(): EvaluationGenerator<boolean>;
	hasSuperBindingEvaluator(): EvaluationGenerator<boolean>;
	withBaseObjectEvaluator(): EvaluationGenerator<StaticJsValue>;
	getThisBindingEvaluator(): EvaluationGenerator<StaticJsValue>;
}
export interface StaticJsError extends StaticJsObject {
	runtimeTypeOf: "error";
}
export interface StaticJsFunction extends StaticJsCallable {
	readonly runtimeTypeOf: "function";
	readonly typeOf: "function";
	readonly strict: boolean;
	readonly initialName: string | null;
	setInitialName(value: string): void;
	getNameAsync(opts?: StaticJsRunTaskOptions): Promise<string>;
	getNameSync(opts?: StaticJsRunTaskOptions): string;
	toNative(opts?: StaticJsCallableToNativeOpts): Function;
}
export interface StaticJsFunctionTypeCreationOptions {
	isConstructor?: boolean;
	length?: number;
	prototype?: StaticJsTypeCreationPrototype;
}
export interface StaticJsGenerator extends StaticJsObject {
	readonly runtimeTypeOf: "generator";
	nextSync(value?: StaticJsValue, opts?: StaticJsRunTaskOptions): StaticJsIteratorResult;
	nextAsync(value?: StaticJsValue, opts?: StaticJsRunTaskOptions): Promise<StaticJsIteratorResult>;
	nextEvaluator(value?: StaticJsValue): EvaluationGenerator<StaticJsIteratorResult>;
	returnSync(value?: StaticJsValue, opts?: StaticJsRunTaskOptions): StaticJsIteratorResult;
	returnAsync(value?: StaticJsValue, opts?: StaticJsRunTaskOptions): Promise<StaticJsIteratorResult>;
	returnEvaluator(value?: StaticJsValue): EvaluationGenerator<StaticJsIteratorResult>;
	throwSync(value: StaticJsValue, opts?: StaticJsRunTaskOptions): StaticJsIteratorResult;
	throwAsync(value: StaticJsValue, opts?: StaticJsRunTaskOptions): Promise<StaticJsIteratorResult>;
	throwEvaluator(value: StaticJsValue): EvaluationGenerator<StaticJsIteratorResult>;
}
export interface StaticJsIterator extends StaticJsObject {
	readonly runtimeTypeOf: "iterator";
	nextSync(opts?: StaticJsRunTaskOptions): StaticJsIteratorResult;
	nextAsync(opts?: StaticJsRunTaskOptions): Promise<StaticJsIteratorResult>;
	nextEvaluator(): EvaluationGenerator<StaticJsIteratorResult>;
}
export interface StaticJsIteratorResult {
	readonly value: StaticJsValue;
	readonly done: boolean;
}
export interface StaticJsMap extends StaticJsObject {
	readonly runtimeTypeOf: "map";
	sizeSync(opts?: StaticJsRunTaskOptions): number;
	sizeAsync(opts?: StaticJsRunTaskOptions): Promise<number>;
	sizeEvaluator(): EvaluationGenerator<number>;
	entriesSync(opts?: StaticJsRunTaskOptions): StaticJsIterator;
	entriesAsync(opts?: StaticJsRunTaskOptions): Promise<StaticJsIterator>;
	entriesEvaluator(): EvaluationGenerator<StaticJsIterator>;
	keysSync(opts?: StaticJsRunTaskOptions): StaticJsIterator;
	keysAsync(opts?: StaticJsRunTaskOptions): Promise<StaticJsIterator>;
	keysEvaluator(): EvaluationGenerator<StaticJsIterator>;
	valuesSync(opts?: StaticJsRunTaskOptions): StaticJsIterator;
	valuesAsync(opts?: StaticJsRunTaskOptions): Promise<StaticJsIterator>;
	valuesEvaluator(): EvaluationGenerator<StaticJsIterator>;
	hasSync(key: StaticJsValue, opts?: StaticJsRunTaskOptions): boolean;
	hasAsync(key: StaticJsValue, opts?: StaticJsRunTaskOptions): Promise<boolean>;
	hasEvaluator(key: StaticJsValue): EvaluationGenerator<boolean>;
	getValueSync(key: StaticJsValue, opts?: StaticJsRunTaskOptions): StaticJsValue;
	getValueAsync(key: StaticJsValue, opts?: StaticJsRunTaskOptions): Promise<StaticJsValue>;
	getValueEvaluator(key: StaticJsValue): EvaluationGenerator<StaticJsValue>;
	setValueSync(key: StaticJsValue, value: StaticJsValue, opts?: StaticJsRunTaskOptions): void;
	setValueAsync(key: StaticJsValue, value: StaticJsValue, opts?: StaticJsRunTaskOptions): Promise<void>;
	setValueEvaluator(key: StaticJsValue, value: StaticJsValue): EvaluationGenerator<void>;
	deleteValueSync(key: StaticJsValue, opts?: StaticJsRunTaskOptions): boolean;
	deleteValueAsync(key: StaticJsValue, opts?: StaticJsRunTaskOptions): Promise<boolean>;
	deleteValueEvaluator(key: StaticJsValue): EvaluationGenerator<boolean>;
	clearSync(opts?: StaticJsRunTaskOptions): void;
	clearAsync(opts?: StaticJsRunTaskOptions): Promise<void>;
	clearEvaluator(): EvaluationGenerator<void>;
	forEachSync(callback: StaticJsCallable, thisArg?: StaticJsValue, opts?: StaticJsRunTaskOptions): void;
	forEachAsync(callback: StaticJsCallable, thisArg?: StaticJsValue, opts?: StaticJsRunTaskOptions): Promise<void>;
	forEachEvaluator(callback: StaticJsCallable, thisArg?: StaticJsValue): EvaluationGenerator<void>;
}
export interface StaticJsModule {
	readonly name: string;
	getExportedNames(opts?: StaticJsRunTaskOptions): string[];
	getExportAsync(exportName: string, opts?: StaticJsRunTaskOptions): Promise<StaticJsValue | null>;
	getExportJsSync(exportName: string, opts?: StaticJsRunTaskOptions): unknown;
	getModuleNamespaceAsync(): Promise<StaticJsObject>;
	getModuleNamespaceJsSync(opts?: StaticJsRunTaskOptions): Record<string, unknown>;
}
export interface StaticJsNull extends StaticJsPrimitive {
	readonly runtimeTypeOf: "null";
	readonly value: null;
}
export interface StaticJsNumber extends StaticJsPrimitive {
	readonly runtimeTypeOf: "number";
	value: number;
}
export interface StaticJsObject extends StaticJsPrimitive {
	getPrototypeOfAsync(opts?: StaticJsRunTaskOptions): Promise<StaticJsObject | null>;
	getPrototypeOfSync(opts?: StaticJsRunTaskOptions): StaticJsObject | null;
	getPrototypeOfEvaluator(): EvaluationGenerator<StaticJsObject | null>;
	setPrototypeOfAsync(prototype: StaticJsObject | null, opts?: StaticJsRunTaskOptions): Promise<boolean>;
	setPrototypeOfSync(prototype: StaticJsObject | null, opts?: StaticJsRunTaskOptions): boolean;
	setPrototypeOfEvaluator(prototype: StaticJsObject | null): EvaluationGenerator<boolean>;
	isExtensibleAsync(opts?: StaticJsRunTaskOptions): Promise<boolean>;
	isExtensibleSync(opts?: StaticJsRunTaskOptions): boolean;
	isExtensibleEvaluator(opts?: StaticJsRunTaskOptions): EvaluationGenerator<boolean>;
	preventExtensionsAsync(opts?: StaticJsRunTaskOptions): Promise<boolean>;
	preventExtensionsSync(opts?: StaticJsRunTaskOptions): boolean;
	preventExtensionsEvaluator(): EvaluationGenerator<boolean>;
	ownPropertyKeysAsync(opts?: StaticJsRunTaskOptions): Promise<StaticJsPropertyKey[]>;
	ownPropertyKeysSync(opts?: StaticJsRunTaskOptions): StaticJsPropertyKey[];
	ownPropertyKeysEvaluator(): EvaluationGenerator<StaticJsPropertyKey[]>;
	ownEnumerableKeysAsync(opts?: StaticJsRunTaskOptions): Promise<string[]>;
	ownEnumerableKeysSync(opts?: StaticJsRunTaskOptions): string[];
	ownEnumerableKeysEvaluator(): EvaluationGenerator<string[]>;
	hasPropertyAsync(key: StaticJsPropertyKey, opts?: StaticJsRunTaskOptions): Promise<boolean>;
	hasPropertySync(key: StaticJsPropertyKey, opts?: StaticJsRunTaskOptions): boolean;
	hasPropertyEvaluator(key: StaticJsPropertyKey): EvaluationGenerator<boolean>;
	hasOwnPropertyAsync(key: StaticJsPropertyKey, opts?: StaticJsRunTaskOptions): Promise<boolean>;
	hasOwnPropertySync(key: StaticJsPropertyKey, opts?: StaticJsRunTaskOptions): boolean;
	hasOwnPropertyEvaluator(key: StaticJsPropertyKey): EvaluationGenerator<boolean>;
	getPropertyAsync(key: StaticJsPropertyKey, opts?: StaticJsRunTaskOptions): Promise<StaticJsPropertyDescriptor | undefined>;
	getPropertySync(key: StaticJsPropertyKey, opts?: StaticJsRunTaskOptions): StaticJsPropertyDescriptor | undefined;
	getPropertyEvaluator(key: StaticJsPropertyKey): EvaluationGenerator<StaticJsPropertyDescriptor | undefined>;
	getOwnPropertyAsync(key: StaticJsPropertyKey, opts?: StaticJsRunTaskOptions): Promise<StaticJsPropertyDescriptor | undefined>;
	getOwnPropertySync(key: StaticJsPropertyKey, opts?: StaticJsRunTaskOptions): StaticJsPropertyDescriptor | undefined;
	getOwnPropertyEvaluator(key: StaticJsPropertyKey): EvaluationGenerator<StaticJsPropertyDescriptor | undefined>;
	defineOwnPropertyAsync(key: StaticJsPropertyKey, descriptor: StaticJsPropertyDescriptorRecord, opts?: StaticJsRunTaskOptions): Promise<boolean>;
	defineOwnPropertySync(key: StaticJsPropertyKey, descriptor: StaticJsPropertyDescriptorRecord, opts?: StaticJsRunTaskOptions): boolean;
	defineOwnPropertyEvaluator(key: StaticJsPropertyKey, descriptor: StaticJsPropertyDescriptorRecord): EvaluationGenerator<boolean>;
	getAsync(key: StaticJsPropertyKey, opts?: StaticJsObjectPropertyAccessRunTaskOptions): Promise<StaticJsValue>;
	getSync(key: StaticJsPropertyKey, opts?: StaticJsObjectPropertyAccessRunTaskOptions): StaticJsValue;
	getEvaluator(key: StaticJsPropertyKey, receiver?: StaticJsValue): EvaluationGenerator<StaticJsValue>;
	getEvaluator(key: StaticJsPropertyKey, opts?: StaticJsObjectPropertyAccessOptions): EvaluationGenerator<StaticJsValue>;
	setAsync(key: StaticJsPropertyKey, value: StaticJsValue, opts?: StaticJsObjectPropertyAccessRunTaskOptions): Promise<boolean>;
	setSync(key: StaticJsPropertyKey, value: StaticJsValue, opts?: StaticJsObjectPropertyAccessRunTaskOptions): boolean;
	setEvaluator(key: StaticJsPropertyKey, value: StaticJsValue, receiver?: StaticJsValue): EvaluationGenerator<boolean>;
	setEvaluator(key: StaticJsPropertyKey, value: StaticJsValue, opts?: StaticJsObjectPropertyAccessOptions): EvaluationGenerator<boolean>;
	deleteAsync(key: StaticJsPropertyKey, opts?: StaticJsRunTaskOptions): Promise<boolean>;
	deleteSync(key: StaticJsPropertyKey, opts?: StaticJsRunTaskOptions): boolean;
	deleteEvaluator(key: StaticJsPropertyKey): EvaluationGenerator<boolean>;
	privateElementFindEvaluator(p: StaticJsPrivateName): EvaluationGenerator<StaticJsPrivateElement | null>;
	privateElementAddEvaluator(element: StaticJsPrivateElement): EvaluationGenerator<void>;
}
export interface StaticJsObjectPropertyAccessOptions {
	receiver?: StaticJsValue;
}
export interface StaticJsPlainObject extends StaticJsObject {
	readonly runtimeTypeOf: "object";
}
export interface StaticJsPrimitive {
	readonly realm: StaticJsRealm;
	readonly typeOf: string;
	readonly runtimeTypeOf: string;
	readonly runtimeTypeCode: StaticJsTypeCode;
	toNative(): unknown;
	toStringSync(): string;
}
export interface StaticJsPrivateElementAccessor extends StaticJsPrivateElementBase {
	kind: "accessor";
	get: StaticJsFunction | undefined;
	set: StaticJsFunction | undefined;
}
export interface StaticJsPrivateElementBase {
	type: "private-element";
	key: StaticJsPrivateName;
	kind: "field" | "method" | "accessor";
}
export interface StaticJsPrivateElementField extends StaticJsPrivateElementBase {
	kind: "field";
	value: StaticJsValue;
}
export interface StaticJsPrivateElementMethod extends StaticJsPrivateElementBase {
	kind: "method";
	value: StaticJsFunction;
}
export interface StaticJsPrivateName {
	type: "private-name";
	description: string;
}
export interface StaticJsPromise extends StaticJsObject {
	readonly runtimeTypeOf: "promise";
	resolve(value: StaticJsValue): void;
	reject(reason: StaticJsValue): void;
	thenSync(onFulfilled?: StaticJsCallable | undefined, onRejected?: StaticJsCallable | undefined, opts?: StaticJsRunTaskOptions): StaticJsPromise;
	thenAsync(onFulfilled?: StaticJsCallable | undefined, onRejected?: StaticJsCallable | undefined, opts?: StaticJsRunTaskOptions): Promise<StaticJsPromise>;
	thenEvaluator(onFulfilled?: StaticJsCallable | undefined, onRejected?: StaticJsCallable | undefined, resultCapability?: StaticJsPromiseCapabilityRecord | true): EvaluationGenerator<StaticJsPromise>;
	thenEvaluator(onFulfilled: StaticJsCallable | undefined, onRejected: StaticJsCallable | undefined, resultCapability: false): EvaluationGenerator<void>;
	catchSync(func: StaticJsCallable | undefined, opts?: StaticJsRunTaskOptions): StaticJsPromise;
	catchAsync(func: StaticJsCallable | undefined, opts?: StaticJsRunTaskOptions): Promise<StaticJsPromise>;
	catchEvaluator(func: StaticJsCallable | undefined): EvaluationGenerator<StaticJsPromise>;
	toNative(): Promise<unknown>;
}
export interface StaticJsPromiseCapabilityRecord {
	promise: StaticJsPromise;
	resolve: StaticJsCallable;
	reject: StaticJsCallable;
}
export interface StaticJsPropertyDescriptorRecord {
	configurable?: boolean;
	enumerable?: boolean;
	value?: StaticJsValue;
	writable?: boolean;
	get?: StaticJsCallable | undefined;
	set?: StaticJsCallable | undefined;
}
export interface StaticJsProxy extends StaticJsObject, StaticJsCallable {
	readonly runtimeTypeOf: "proxy";
	toNative(opts?: StaticJsCallableToNativeOpts): unknown;
	get proxyTarget(): StaticJsObject | null;
	validateNonRevokedProxyEvaluator(): EvaluationGenerator<void>;
}
export interface StaticJsProxyHandlers {
	getPrototypeOf?(target: StaticJsObject): MaybeEvaluationGenerator<StaticJsObject | null>;
	setPrototypeOf?(target: StaticJsObject, prototype: StaticJsObject | null): MaybeEvaluationGenerator<boolean>;
	isExtensible?(target: StaticJsObject): MaybeEvaluationGenerator<boolean>;
	preventExtensions?(target: StaticJsObject): MaybeEvaluationGenerator<boolean>;
	getOwnPropertyDescriptor?(target: StaticJsObject, key: StaticJsPropertyKey): MaybeEvaluationGenerator<StaticJsPropertyDescriptor | undefined>;
	defineProperty?(target: StaticJsObject, key: StaticJsPropertyKey, desc: StaticJsPropertyDescriptorRecord): MaybeEvaluationGenerator<boolean>;
	has?(target: StaticJsObject, key: StaticJsPropertyKey): MaybeEvaluationGenerator<boolean>;
	get?(target: StaticJsObject, key: StaticJsPropertyKey, receiver: StaticJsValue): MaybeEvaluationGenerator<StaticJsValue>;
	set?(target: StaticJsObject, key: StaticJsPropertyKey, value: StaticJsValue, receiver: StaticJsValue): MaybeEvaluationGenerator<boolean>;
	deleteProperty?(target: StaticJsObject, key: StaticJsPropertyKey): MaybeEvaluationGenerator<boolean>;
	ownKeys?(target: StaticJsObject): MaybeEvaluationGenerator<StaticJsPropertyKey[]>;
	apply?(target: StaticJsCallable, thisArgument: StaticJsValue, argArray: StaticJsValue[]): MaybeEvaluationGenerator<StaticJsValue>;
	construct?(target: StaticJsCallable, argArray: StaticJsValue[], newTarget: StaticJsCallable): MaybeEvaluationGenerator<StaticJsObject>;
}
export interface StaticJsRealmEvaluateScriptOptions extends StaticJsRealmEvaluateSourceOptions {
	/**
	 * Whether to support top-level await in the script.
	 * If true, evaluateScript will always return a promise.
	 * If "auto", evaluateScript will return a promise if top-level await is used, otherwise it will return the result directly.
	 * If false or omitted, top-level await is not supported and will throw a syntax error if used.
	 *
	 * Default: false
	 */
	topLevelAwait?: boolean | "auto";
	/**
	 * Whether to enable strict mode for the script. If true, the script will be evaluated in strict mode.
	 * If false or omitted, the script will inherit strict mode from its directives.
	 *
	 * Default: false
	 */
	strict?: boolean;
}
export interface StaticJsRealmGlobalAccessorPropertyDecl {
	readonly configurable?: boolean;
	readonly enumerable?: boolean;
	get?(): MaybeEvaluationGenerator<unknown>;
	set?(value: unknown): MaybeEvaluationGenerator<void>;
}
export interface StaticJsRealmGlobalDataPropertyDecl {
	readonly configurable?: boolean;
	readonly enumerable?: boolean;
	readonly writable?: boolean;
	readonly value: unknown;
}
export interface StaticJsRealmGlobalDecl {
	properties: Record<string, StaticJsRealmGlobalDeclProperty>;
}
export interface StaticJsRealmGlobalValue {
	value: object;
}
/**
 * A host-defined ECMAScript module
 */
export interface StaticJsRealmModuleExports {
	exports: Record<string, unknown>;
}
/**
 * Options for creating a StaticJsRealm.
 */
export interface StaticJsRealmOptions {
	/**
	 * Settings for the global 'this' object in the realm.
	 */
	globalThis?: StaticJsRealmGlobalOption;
	/**
	 * Settings for the global object in the realm.
	 */
	global?: StaticJsRealmGlobalOption;
	/**
	 * Statically defined ECMA Modules.
	 */
	modules?: Record<string, StaticJsModuleResolution>;
	/**
	 * Optional hooks to override engine behavior for various operations.
	 */
	hooks?: StaticJsRealmHookOptions;
	/**
	 * A resolver function to resolve imported ECMA Modules not found in {@link StaticJsRealmOptions.modules}
	 */
	resolveImportedModule?: StaticJsModuleResolver;
	/**
	 * Invoked when the realm wants to run a task.
	 *
	 * The implementation should call .next() on the evaluator until it is done.
	 * This may be done synchronously or asynchronously.
	 *
	 * Used for
	 * {@link IStaticJsRealm.evaluateExpression},
	 * {@link IStaticJsRealm.evaluateScriptSync}, and
	 * {@link IStaticJsRealm.evaluateModule} when the
	 * {@link StaticJsRunTaskOptions.runTask} option is not specified.
	 */
	runTask?: StaticJsTaskRunner;
	/**
	 * Invoked when the realm wants to run a task synchronously.
	 *
	 * The implementation should call .next() on the evaluator until it is done.
	 * This must be done synchronously.  Failure to complete the task will result in an error.
	 *
	 * Used for {@link IStaticJsRealm.evaluateExpressionSync} and
	 * {@link IStaticJsRealm.evaluateScriptSync} when the
	 * {@link StaticJsRunTaskOptions.runTask} option is not specified.
	 */
	runTaskSync?: StaticJsTaskRunner;
	/**
	 * Default host-access policy applied to `realm.types.toStaticJsValue(value)` calls
	 * that do not pass their own opts. When explicit opts are passed, they fully
	 * replace this default (no field-level merging).
	 */
	hostAccessDefaults?: HostAccessOptions;
}
/**
 * Options for running tasks in the StaticJs runtime.
 */
export interface StaticJsRunTaskOptions {
	/**
	 * The task runner to use.
	 *
	 * If specified, this will be used instead of {@link import('./factories/StaticJsRealm').StaticJsRealmOptions.runTask}.
	 *
	 * This may not be called immediately.  The task will be run when it is reached in the queue.
	 * @param task The task to run.
	 */
	runTask?: StaticJsTaskRunner;
}
export interface StaticJsSet extends StaticJsObject {
	readonly runtimeTypeOf: "set";
	sizeSync(opts?: StaticJsRunTaskOptions): number;
	sizeAsync(opts?: StaticJsRunTaskOptions): Promise<number>;
	sizeEvaluator(): EvaluationGenerator<number>;
	keysSync(opts?: StaticJsRunTaskOptions): StaticJsIterator;
	keysAsync(opts?: StaticJsRunTaskOptions): Promise<StaticJsIterator>;
	keysEvaluator(): EvaluationGenerator<StaticJsIterator>;
	valuesSync(opts?: StaticJsRunTaskOptions): StaticJsIterator;
	valuesAsync(opts?: StaticJsRunTaskOptions): Promise<StaticJsIterator>;
	valuesEvaluator(): EvaluationGenerator<StaticJsIterator>;
	entriesSync(opts?: StaticJsRunTaskOptions): StaticJsIterator;
	entriesAsync(opts?: StaticJsRunTaskOptions): Promise<StaticJsIterator>;
	entriesEvaluator(): EvaluationGenerator<StaticJsIterator>;
	hasSync(value: StaticJsValue, opts?: StaticJsRunTaskOptions): boolean;
	hasAsync(value: StaticJsValue, opts?: StaticJsRunTaskOptions): Promise<boolean>;
	hasEvaluator(value: StaticJsValue): EvaluationGenerator<boolean>;
	addValueSync(value: StaticJsValue, opts?: StaticJsRunTaskOptions): void;
	addValueAsync(value: StaticJsValue, opts?: StaticJsRunTaskOptions): Promise<void>;
	addValueEvaluator(value: StaticJsValue): EvaluationGenerator<void>;
	deleteValueSync(value: StaticJsValue, opts?: StaticJsRunTaskOptions): boolean;
	deleteValueAsync(value: StaticJsValue, opts?: StaticJsRunTaskOptions): Promise<boolean>;
	deleteValueEvaluator(value: StaticJsValue): EvaluationGenerator<boolean>;
	clearSync(opts?: StaticJsRunTaskOptions): void;
	clearAsync(opts?: StaticJsRunTaskOptions): Promise<void>;
	clearEvaluator(): EvaluationGenerator<void>;
	forEachSync(callback: StaticJsFunction, thisArg?: StaticJsValue, opts?: StaticJsRunTaskOptions): void;
	forEachAsync(callback: StaticJsFunction, thisArg?: StaticJsValue, opts?: StaticJsRunTaskOptions): Promise<void>;
	forEachEvaluator(callback: StaticJsFunction, thisArg?: StaticJsValue): EvaluationGenerator<void>;
	differenceSync(otherSet: StaticJsValue, opts?: StaticJsRunTaskOptions): StaticJsValue;
	differenceAsync(otherSet: StaticJsValue, opts?: StaticJsRunTaskOptions): Promise<StaticJsValue>;
	differenceEvaluator(otherSet: StaticJsValue): EvaluationGenerator<StaticJsValue>;
	intersectionSync(otherSet: StaticJsValue, opts?: StaticJsRunTaskOptions): StaticJsValue;
	intersectionAsync(otherSet: StaticJsValue, opts?: StaticJsRunTaskOptions): Promise<StaticJsValue>;
	intersectionEvaluator(otherSet: StaticJsValue): EvaluationGenerator<StaticJsValue>;
	isDisjointFromSync(otherSet: StaticJsValue, opts?: StaticJsRunTaskOptions): boolean;
	isDisjointFromAsync(otherSet: StaticJsValue, opts?: StaticJsRunTaskOptions): Promise<boolean>;
	isDisjointFromEvaluator(otherSet: StaticJsValue): EvaluationGenerator<boolean>;
	isSubsetOfSync(otherSet: StaticJsValue, opts?: StaticJsRunTaskOptions): boolean;
	isSubsetOfAsync(otherSet: StaticJsValue, opts?: StaticJsRunTaskOptions): Promise<boolean>;
	isSubsetOfEvaluator(otherSet: StaticJsValue): EvaluationGenerator<boolean>;
	isSupersetOfSync(otherSet: StaticJsValue, opts?: StaticJsRunTaskOptions): boolean;
	isSupersetOfAsync(otherSet: StaticJsValue, opts?: StaticJsRunTaskOptions): Promise<boolean>;
	isSupersetOfEvaluator(otherSet: StaticJsValue): EvaluationGenerator<boolean>;
	symmetricDifferenceSync(otherSet: StaticJsValue, opts?: StaticJsRunTaskOptions): StaticJsValue;
	symmetricDifferenceAsync(otherSet: StaticJsValue, opts?: StaticJsRunTaskOptions): Promise<StaticJsValue>;
	symmetricDifferenceEvaluator(otherSet: StaticJsValue): EvaluationGenerator<StaticJsValue>;
	unionSync(otherSet: StaticJsValue, opts?: StaticJsRunTaskOptions): StaticJsValue;
	unionAsync(otherSet: StaticJsValue, opts?: StaticJsRunTaskOptions): Promise<StaticJsValue>;
	unionEvaluator(otherSet: StaticJsValue): EvaluationGenerator<StaticJsValue>;
}
export interface StaticJsString extends StaticJsPrimitive {
	readonly runtimeTypeOf: "string";
	value: string;
}
export interface StaticJsSymbol extends StaticJsObject {
	readonly runtimeTypeOf: "symbol";
	readonly value: symbol;
	readonly description: string | undefined;
	toNative(): symbol;
}
/**
 * A task in the StaticJs runtime.
 *
 * Tasks are implemented as generators.  Call .next() to run a single operation in the task.
 * Call it repeatedly until it returns { done: true }.
 *
 * Task execution can be done asynchronously, with pauses between operations,
 */
export interface StaticJsTaskIterator {
	/**
	 * The callee of the task, which indicates how the task was triggered.
	 */
	readonly calleeType: StaticJsTaskCalleeType;
	/**
	 * Whether the task is for an async operation.
	 *
	 * Async tasks are allowed to not fully drain their iterator before the runTask call returns.
	 */
	readonly async: boolean;
	/**
	 * The type of the current task, either "macrotask" or "microtask".
	 */
	readonly currentTaskType: StaticJsTaskType | null;
	/**
	 * The unique identifier for the current task.
	 * This will change as more microtasks are ran.
	 */
	readonly currentTaskId: string | null;
	/**
	 * Whether the task has completed execution.
	 *
	 * This will return true if the task ran to completion, or if it was aborted.
	 */
	get done(): boolean;
	/**
	 * Whether the task has been aborted.
	 */
	get aborted(): boolean;
	/**
	 * Information on the current queued operation to be evaluated by a call to `.next()`.
	 *
	 * If the task is done, this will be null.
	 */
	get operation(): StaticJsTaskIteratorOperation | null;
	/**
	 * The location of the current operation queued for evaluation.
	 */
	get location(): StaticJsTaskSourceLocation | null;
	/**
	 * The stack frames of the currently executing task, with the top of the stack at index 0.
	 */
	get stack(): readonly StaticJsTaskIteratorStackFrame[];
	/**
	 * The variable scopes of the currently executing task, with the innermost scope at index 0.
	 */
	get scopes(): readonly StaticJsTaskScopeFrame[];
	/**
	 * Evaluate the current operation and proceed the iterator to the next one.
	 */
	next(): IteratorResult<void, void>;
	/**
	 * Raise an error at the current operation.
	 *
	 * If the error is a StaticJsRuntimeError, the executing code WILL be able to catch it.  Otherwise, the error will bubble up to the promise
	 * representing the evaluation of the task.
	 * @param error The error to raise.
	 */
	throw(error: unknown): IteratorResult<void, void>;
	/**
	 * Abort the evaluation of this task.
	 *
	 * The exception will be raised on the promise representating the evaluation.
	 * If no error is specified, a {@link import("../../errors/StaticJsTaskAbortedError.js").StaticJsTaskAbortedError} will be used.
	 * @param error The error to raise.  If this is a string, it will be wrapped in a {@link import("../../errors/StaticJsTaskAbortedError.js").StaticJsTaskAbortedError}.
	 */
	abort(error?: unknown): void;
}
export interface StaticJsTaskIteratorOperation {
	/**
	 * Gets the type of the current operation queued for evaluation.
	 */
	readonly operationType: string;
}
export interface StaticJsTaskIteratorStackFrame {
	readonly depth: number;
	readonly sourceLocation: StaticJsTaskSourceLocation | null;
	readonly function: StaticJsFunction | null;
}
/**
 * Information on a variable scope frame for a static JavaScript task.
 */
export interface StaticJsTaskScopeFrame {
	readonly name: string;
	readonly type: StaticJsTaskScopeFrameType;
	getVariables(opts?: StaticJsRunTaskOptions): readonly StaticJsTaskScopeVariable[];
}
export interface StaticJsTaskScopeVariable {
	readonly name: string;
	readonly value: StaticJsValue | null;
}
export interface StaticJsTaskSourceLocation {
	/**
	 * The name of the source file of the current location in the source code.
	 */
	sourceName: string;
	/**
	 * The 1-based line number of the current location in the source code.
	 */
	line: number;
	/**
	 * The 0-based column number of the current location in the source code.
	 */
	column: number;
	/**
	 * The 0-based character index of the current location in the source code.
	 */
	character: number;
}
export interface StaticJsTypeFactory {
	readonly symbols: IntrinsicSymbols;
	readonly symbolRegistry: Map<string, StaticJsSymbol>;
	readonly undefined: StaticJsUndefined;
	readonly null: StaticJsNull;
	readonly true: StaticJsBoolean;
	readonly false: StaticJsBoolean;
	readonly zero: StaticJsNumber;
	readonly NaN: StaticJsNumber;
	readonly Infinity: StaticJsNumber;
	boolean(value: boolean): StaticJsBoolean;
	number(value: number): StaticJsNumber;
	string(value: string): StaticJsString;
	symbol(description?: string | symbol): StaticJsSymbol;
	object(properties?: Record<string, StaticJsPropertyDescriptorRecord> | Map<StaticJsPropertyKey, StaticJsPropertyDescriptorRecord>, prototype?: StaticJsTypeCreationPrototype): StaticJsPlainObject;
	array(itemsOrLength?: StaticJsValue[] | number): StaticJsArray;
	function(name: string, func: (this: StaticJsValue, ...args: StaticJsValue[]) => MaybeEvaluationGenerator<StaticJsValue>, opts?: StaticJsFunctionTypeCreationOptions): StaticJsFunction;
	error(errorType: WellKnownErrorName, message: string): StaticJsObject;
	error(message: string): StaticJsObject;
	proxy(target: StaticJsProxyTarget, handlers: StaticJsProxyHandlers): StaticJsProxy;
	toStaticJsValue(value: (...args: unknown[]) => unknown, opts?: HostAccessArg): StaticJsFunction;
	toStaticJsValue(value: boolean): StaticJsBoolean;
	toStaticJsValue(value: number): StaticJsNumber;
	toStaticJsValue(value: string): StaticJsString;
	toStaticJsValue(value: unknown[], opts?: HostAccessArg): StaticJsArray;
	toStaticJsValue(value: object, opts?: HostAccessArg): StaticJsPlainObject;
	toStaticJsValue(value: Function, opts?: HostAccessArg): StaticJsFunction;
	toStaticJsValue(value: symbol): StaticJsSymbol;
	toStaticJsValue(value: null): StaticJsNull;
	toStaticJsValue(value: undefined): StaticJsUndefined;
	toStaticJsValue(value: unknown, opts?: HostAccessArg): StaticJsValue;
}
export interface StaticJsUndefined extends StaticJsPrimitive {
	readonly runtimeTypeOf: "undefined";
	readonly value: undefined;
}
export interface SyntaxErrorLocation {
	line: number;
	column: number;
	index: number;
}
export interface TimeBoundTaskRunnerOptions {
	/**
	 * The maximum time, in milliseconds, that a synchronous task is allowed to run for.
	 * @default 5_000
	 */
	maxRunTime?: number;
	/**
	 * The maximum time, in milliseconds, that a single task (macrotask or microtask)
	 * is allowed to run for before being aborted.
	 * If not specified, the default is no limit.
	 * @default Infinity
	 */
	maxTaskTime?: number;
}
export interface TimeSharingTaskRunnerOptions {
	/**
	 * The maximum number of operations to execute before yielding back to the caller.
	 * If not specified, the default is 10,000.
	 */
	operationsPerIteration?: number;
	/**
	 * The amount of time, in milliseconds, to wait before resuming the task.
	 * If not specified, the default is 100 milliseconds.
	 */
	yieldTime?: number;
	/**
	 * The maximum time, in milliseconds, that the entire evaluation is allowed to run for.
	 * If not specified, the default is no limit.
	 */
	maxRunTime?: number;
	/**
	 * The maximum time, in milliseconds, that a single task (macrotask or microtask)
	 * is allowed to run for before being aborted.
	 * If not specified, the default is no limit.
	 */
	maxTaskTime?: number;
}
export type Completion = BreakCompletion | ContinueCompletion | NormalCompletion | ReturnCompletion | ThrowCompletion;
export type EvaluationGenerator<TReturn = Completion.Normal> = Generator<EvaluatorCommandBase, TReturn, Completion.Normal>;
/**
 * Argument option for specifying host access level to a host object in the sandbox.
 */
export type HostAccessArg = HostAccessOptions | HostAccessRootQueryFunction;
/**
 * Policy for child host objects reached from a parent host object. See HostAccessOptions.childPolicy.
 * If "inherit", the child uses the same policy as the parent (sticky).
 * If "default", the child uses the realm default policy.
 * If "false", the child instead resolves to undefined.
 * If a function, it will be invoked with the child host object to determine the policy. Decide on a per-object basis.
 */
export type HostAccessChildOptions = HostAccessQueryResult | HostAccessQueryFunction;
/**
 * Query function to check whether the given child of a host object should be exposed and at what level.
 * If "inherit", the child uses the same policy as the parent (sticky).
 * If "default", the child uses the realm default policy.
 * If false, the child is not exposed — it resolves to `undefined`.
 * If an object, that child becomes a new sub-root governed by these options.
 */
export type HostAccessQueryFunction = (childHostObj: object) => HostAccessQueryResult;
export type HostAccessQueryResult = "inherit" | "default" | boolean | HostAccessOptions | StaticJsValue;
/**
 * Query function to check whether the given host object should be exposed and at what level.
 * If "default", the realm's defaults are used.
 * If a StaticJsValue, the returned value will be used for the host object.
 * If an object, that host object becomes a new root governed by these options.
 */
export type HostAccessRootQueryFunction = (childHostObj: object) => "default" | HostAccessOptions | StaticJsValue;
export type HostAccessStubType = "array" | "error";
export type Intrinsics = Readonly<IntrinsicsRecord>;
export type MaybeEvaluationGenerator<T> = T | EvaluationGenerator<T>;
export type NativeErrors = Pick<Intrinsics, "EvalError" | "RangeError" | "ReferenceError" | "SyntaxError" | "TypeError" | "URIError">;
export type Prototypes = Pick<Intrinsics, "AggregateError.prototype" | "Array.prototype" | "ArrayIteratorPrototype" | "AsyncFromSyncIteratorPrototype" | "AsyncFunction.prototype" | "AsyncGeneratorFunction.prototype" | "AsyncGeneratorPrototype" | "AsyncIteratorPrototype" | "Boolean.prototype" | "Error.prototype" | "EvalError.prototype" | "ForInIteratorPrototype" | "Function.prototype" | "GeneratorFunction.prototype" | "GeneratorPrototype" | "Iterator.prototype" | "IteratorHelperPrototype" | "Map.prototype" | "Number.prototype" | "Object.prototype" | "Promise.prototype" | "RangeError.prototype" | "ReferenceError.prototype" | "Set.prototype" | "SetIteratorPrototype" | "String.prototype" | "StringIteratorPrototype" | "Symbol.prototype" | "SyntaxError.prototype" | "TypeError.prototype" | "URIError.prototype">;
export type StaticJsEvaluator<T = unknown> = EvaluationGenerator<T> | (() => EvaluationGenerator<T>);
/**
 * Valid types for an ECMAScript Module resolution.
 */
export type StaticJsModuleResolution = StaticJsRealmModuleExports | StaticJsModule | StaticJsModuleImplementation | string;
/**
 * A factory function to resolve an imported ECMAScript Module.
 */
export type StaticJsModuleResolver = (specifier: string, referencingModule: StaticJsModule) => Promise<StaticJsModuleResolution | null>;
export type StaticJsObjectPropertyAccessRunTaskOptions = StaticJsObjectPropertyAccessOptions & StaticJsRunTaskOptions;
export type StaticJsPrivateElement = StaticJsPrivateElementField | StaticJsPrivateElementMethod | StaticJsPrivateElementAccessor;
export type StaticJsPropertyDescriptor = StaticJsDataPropertyDescriptor | StaticJsAccessorPropertyDescriptor;
export type StaticJsPropertyKey = string | StaticJsSymbol;
export type StaticJsProxyTarget = StaticJsObject | StaticJsCallable | "object" | "function";
export type StaticJsRealmGlobalDeclProperty = StaticJsRealmGlobalDataPropertyDecl | StaticJsRealmGlobalAccessorPropertyDecl;
export type StaticJsRealmGlobalOption = StaticJsRealmGlobalDecl | StaticJsRealmGlobalValue | StaticJsRealmGlobalFactory;
export type StaticJsRealmHookOptions = PartialDeep<RealmHooks>;
export type StaticJsScalar = StaticJsNull | StaticJsString | StaticJsNumber | StaticJsBoolean | StaticJsSymbol | StaticJsUndefined;
/**
 * A function to run a task in the realm.
 *
 * The implementation should call .next() on the generator until it is done.
 * This may be done synchronously or asynchronously.
 */
export type StaticJsTaskRunner = (task: StaticJsTaskIterator) => void;
export type StaticJsTaskScopeFrameType = "block" | "function" | "module" | "global";
/**
 * The type of a task in the StaticJs runtime.
 *
 * - macrotask
 *   A normal task triggered by evaluateScript, evaluateExpression, or evaluateModule
 * - microtask
 *   A followup for a promise resolution or similar, which runs after the current task completes but before the next macrotask starts.
 *
 */
export type StaticJsTaskType = "macrotask" | "microtask";
export type StaticJsTypeCreationPrototype = StaticJsObject | StaticJsNull | null;
export type StaticJsValue = StaticJsScalar | StaticJsPlainObject | StaticJsObject | StaticJsArray | StaticJsFunction;
export type WellKnownErrorName = (typeof WellKnownErrorNames)[number];
interface BreakCompletion {
	readonly type: "break";
	readonly target: string | null;
	readonly value: CompletionValue;
}
interface ContinueCompletion {
	readonly type: "continue";
	readonly target: string | null;
	readonly value: CompletionValue;
}
interface EvaluationOptions {
	realm?: StaticJsRealm;
	runTask?: StaticJsTaskRunner;
	sourceName?: string;
}
interface EvaluatorCommandBase {
	command: string;
}
interface MathHooks {
	acos: MathAcosHook;
	acosh: MathAcoshHook;
	asin: MathAsinHook;
	asinh: MathAsinhHook;
	atan: MathAtanHook;
	atan2: MathAtan2Hook;
	atanh: MathAtanhHook;
	cbrt: MathCbrtHook;
	cos: MathCosHook;
	cosh: MathCoshHook;
	exp: MathExpHook;
	expm1: MathExpm1Hook;
	hypot: MathHypotHook;
	log: MathLogHook;
	log10: MathLog10Hook;
	log1p: MathLog1pHook;
	log2: MathLog2Hook;
	random: MathRandomHook;
	sin: MathSinHook;
	sinh: MathSinhHook;
	sqrt: MathSqrtHook;
	tan: MathTanHook;
	tanh: MathTanhHook;
}
interface ReturnCompletion {
	readonly type: "return";
	readonly value: StaticJsValue;
}
interface StaticJsConfig {
	/**
	 * The task runner used to run async tasks in the realm.
	 */
	readonly runTask: StaticJsTaskRunner;
	/**
	 * The task runner used to run sync tasks in the realm.
	 */
	readonly runTaskSync: StaticJsTaskRunner;
	/**
	 * Default host-access policy applied to `realm.types.toStaticJsValue(value)` calls
	 * that do not pass their own opts. When explicit opts are passed, they fully
	 * replace this default (no field-level merging).
	 */
	readonly hostAccessDefaults?: HostAccessOptions;
}
interface StaticJsEnvironmentReferenceRecord extends StaticJsPopulatedReferenceRecord {
	base: StaticJsEnvironmentRecord;
	referencedName: string;
}
interface StaticJsModuleImplementation extends StaticJsModule {
	readonly name: string;
	readonly status: StaticJsModuleStatus;
	linkModules(): Promise<void>;
	moduleDeclarationInstantiationEvaluator(): EvaluationGenerator<void>;
	moduleEvaluationEvaluator(): EvaluationGenerator<void | Promise<void>>;
	resolveExportEvaluator(exportName: string, resolveSet?: Set<string>): EvaluationGenerator<StaticJsResolvedBinding>;
	getExportedNamesEvaluator(exportStarSet?: Set<string>): EvaluationGenerator<string[]>;
	getOwnBindingValueEvaluator(bindingName: string): EvaluationGenerator<StaticJsValue | null>;
	getModuleNamespaceEvaluator(): EvaluationGenerator<StaticJsObject>;
}
interface StaticJsModuleResolvedBinding {
	module: StaticJsModuleImplementation;
	bindingName: string | BindingNameNamespace;
}
interface StaticJsNonPrivatePropertyReferenceRecord {
	referencedName: string | StaticJsValue;
	strict: boolean;
	thisValue: StaticJsValue | null;
	base: StaticJsValue;
}
interface StaticJsPopulatedReferenceRecord {
	referencedName: string | StaticJsValue | StaticJsPrivateName;
	strict: boolean;
	thisValue: StaticJsValue | null;
	base: StaticJsEnvironmentRecord | StaticJsValue;
}
interface StaticJsPrivatePropertyPopulatedReferenceRecord {
	referencedName: StaticJsPrivateName;
	strict: boolean;
	thisValue: StaticJsValue | null;
	base: StaticJsValue;
}
interface StaticJsRealm {
	/**
	 * Configuration options the realm was instantiated with.
	 */
	readonly config: StaticJsConfig;
	/**
	 * The type factory for the realm.
	 */
	readonly types: StaticJsTypeFactory;
	/**
	 * The intrinsics of the realm.
	 */
	readonly intrinsics: Intrinsics;
	/**
	 * The global-scope global object of the realm.
	 */
	readonly global: StaticJsObject;
	/**
	 * The global-scope `this` value of the realm.
	 */
	readonly globalThis: StaticJsValue;
	/**
	 * Evaluates the expression in the realm, returning a promise that resolves to the result.
	 * @param expression The expression to evaluate.
	 * @param opts Options for running the task.
	 */
	evaluateExpression(expression: string, opts?: StaticJsRealmEvaluateSourceOptions): Promise<StaticJsValue>;
	/**
	 * Evaluates the expression in the realm synchronously, returning the result.
	 * This cannot be called if a task is already running.
	 * @param expression The expression to evaluate.
	 * @param opts Options for running the task.
	 */
	evaluateExpressionSync(expression: string, opts?: StaticJsRealmEvaluateSourceOptions): StaticJsValue;
	/**
	 * Runs the given script in the realm, returning a promise that resolves to the result.
	 * @param script The script to run.
	 * @param opts Options for running the task.
	 */
	evaluateScript(script: string, opts?: StaticJsRealmEvaluateScriptOptions): Promise<StaticJsValue>;
	/**
	 * Evaluates the script in the realm synchronously, returning the result.
	 * This cannot be called if a task is already running.
	 * @param script The script to evaluate.
	 * @param opts Options for running the task.
	 */
	evaluateScriptSync(script: string, opts?: StaticJsRealmEvaluateScriptSyncOptions): StaticJsValue;
	/**
	 * Evaluates a module in the realm, returning a promise that resolves to the module.
	 *
	 * Note: Async modules may invoke more than one task.
	 * @param code The code of the module to evaluate.
	 * @param opts Options for running the task.
	 */
	evaluateModule(code: string, opts?: StaticJsRealmEvaluateSourceOptions): Promise<StaticJsModule>;
	/**
	 * Returns a promise that resolves when the current task, and all resulting microtasks, have completed.
	 *
	 * The promise will reject if a task or microtask throws an exception or encounters an evaluation error.
	 */
	awaitCurrentTask(): Promise<void>;
	/**
	 * Returns a promise that resolves when the realm is idle, i.e. there are no tasks or microtasks remaining to be processed.
	 */
	awaitIdle(): Promise<void>;
	/**
	 * The global-scope Environment of the realm.
	 * @internal
	 */
	readonly globalEnv: StaticJsEnvironmentRecord;
	/**
	 * The environment record for the global object.
	 * @internal
	 */
	readonly objectEnv: StaticJsEnvironmentRecord;
	/**
	 * The environment record for declarative bindings.
	 * @internal
	 */
	readonly declarativeRecord: StaticJsEnvironmentRecord;
	/**
	 * Engine behavior hooks for the host.
	 * @internal
	 */
	readonly hooks: RealmHooks;
	/**
	 * Raises an uncaught error in the realm.
	 * @internal
	 * @param error The error to raise.
	 * @returns A function that, when called, will clear the uncaught error.
	 */
	raiseUnhandledRejection(error: StaticJsValue): () => void;
	/**
	 * A function to resolve an imported ECMAScript Module given a referencing module
	 * and a specifier.
	 * @internal
	 * @param referencingModule
	 * @param specifier
	 */
	resolveImportedModule(specifier: string, referencingModule: StaticJsModule): Promise<StaticJsModuleImplementation | null>;
	/**
	 * Enqueues a promise job to be executed.
	 * @internal
	 * @param evaluator The evaluator to enqueue.
	 */
	enqueuePromiseJob(evaluator: StaticJsEvaluator<void>): void;
	/**
	 * Invoke the given evaluator synchronously, returning the result.
	 * @internal
	 * @param evaluator The evaluator to invoke.
	 */
	invokeEvaluatorSync<TReturn>(evaluator: StaticJsEvaluator<TReturn>, opts?: StaticJsRunTaskOptions): TReturn;
	/**
	 * Invokes the given evaluator asynchronously, returning a promise that resolves to the result.
	 * TODO: If there is a current task running, inline this invocation into that task.  Else, start it as a macrotask.
	 * @internal
	 * @param evaluator The evaluator to invoke.
	 */
	invokeEvaluatorAsync<TReturn>(evaluator: StaticJsEvaluator<TReturn>, opts?: StaticJsRunTaskOptions): Promise<TReturn>;
}
interface StaticJsRealm$1 {
	(opts?: StaticJsRealmOptions): StaticJsRealm;
	new (opts?: StaticJsRealmOptions): StaticJsRealm;
}
interface StaticJsRealmEvaluateSourceOptions extends StaticJsRunTaskOptions {
	/**
	 * The name of the source to use for the task.  This is used in stack traces and debugging.
  `   */
	sourceName?: string;
}
interface StaticJsRealmGlobalFactory {
	(types: StaticJsTypeFactory): StaticJsObject;
}
interface StaticJsUnresolvedReferenceRecord {
	referencedName: string;
	strict: boolean;
	thisValue: null;
	base: null;
}
interface ThrowCompletion {
	readonly type: "throw";
	readonly value: StaticJsValue;
}
type AbruptCompletion = BreakCompletion | ContinueCompletion | ReturnCompletion | ThrowCompletion;
type BindingNameNamespace = typeof BindingNameNamespace;
type CompletionValue = StaticJsValue | StaticJsReferenceRecord | null;
type ControlFlowCompletion = BreakCompletion | ContinueCompletion | ReturnCompletion;
type MathAcosHook = (this: undefined, realm: StaticJsRealm, value: number) => number;
type MathAcoshHook = (this: undefined, realm: StaticJsRealm, value: number) => number;
type MathAsinHook = (this: undefined, realm: StaticJsRealm, value: number) => number;
type MathAsinhHook = (this: undefined, realm: StaticJsRealm, value: number) => number;
type MathAtan2Hook = (this: undefined, realm: StaticJsRealm, y: number, x: number) => number;
type MathAtanHook = (this: undefined, realm: StaticJsRealm, value: number) => number;
type MathAtanhHook = (this: undefined, realm: StaticJsRealm, value: number) => number;
type MathCbrtHook = (this: undefined, realm: StaticJsRealm, value: number) => number;
type MathCosHook = (this: undefined, realm: StaticJsRealm, value: number) => number;
type MathCoshHook = (this: undefined, realm: StaticJsRealm, value: number) => number;
type MathExpHook = (this: undefined, realm: StaticJsRealm, value: number) => number;
type MathExpm1Hook = (this: undefined, realm: StaticJsRealm, value: number) => number;
type MathHypotHook = (this: undefined, realm: StaticJsRealm, ...values: number[]) => number;
type MathLog10Hook = (this: undefined, realm: StaticJsRealm, value: number) => number;
type MathLog1pHook = (this: undefined, realm: StaticJsRealm, value: number) => number;
type MathLog2Hook = (this: undefined, realm: StaticJsRealm, value: number) => number;
type MathLogHook = (this: undefined, realm: StaticJsRealm, value: number) => number;
type MathRandomHook = (this: undefined, realm: StaticJsRealm) => number;
type MathSinHook = (this: undefined, realm: StaticJsRealm, value: number) => number;
type MathSinhHook = (this: undefined, realm: StaticJsRealm, value: number) => number;
type MathSqrtHook = (this: undefined, realm: StaticJsRealm, value: number) => number;
type MathTanHook = (this: undefined, realm: StaticJsRealm, value: number) => number;
type MathTanhHook = (this: undefined, realm: StaticJsRealm, value: number) => number;
type NormalCompletion = CompletionValue;
type PartialDeep<T> = T extends Function ? T : T extends object ? {
	[K in keyof T]?: PartialDeep<T[K]>;
} : T;
type StaticJsModuleStatus = "uninstantiated" | "instantiating" | "instantiated" | "evaluating" | "evaluated";
type StaticJsPropertyReferenceRecord = StaticJsPrivatePropertyPopulatedReferenceRecord | StaticJsNonPrivatePropertyReferenceRecord;
type StaticJsRealm$2 = StaticJsRealm;
type StaticJsRealmEvaluateScriptSyncOptions = Omit<StaticJsRealmEvaluateScriptOptions, "topLevelAwait">;
type StaticJsReferenceRecord = StaticJsUnresolvedReferenceRecord | StaticJsPropertyReferenceRecord | StaticJsEnvironmentReferenceRecord;
type StaticJsResolvedBinding = StaticJsModuleResolvedBinding | "ambiguous" | null;
type StaticJsTaskCalleeType = "evaluate" | "host";

export {
	StaticJsEvaluator as StaticJsRealmEvaluator,
	StaticJsRealm$2 as StaticJsRealm,
	StaticJsRealmEvaluateScriptSyncOptions as StaticJsEvaluateScriptSyncOptions,
};

export {};
