import { it, describe } from "vitest";
import { createTestHandler } from "../../../create-test-handler.js";

describe("zipKeyed", () => {
it("basic-longest.js", createTestHandler("built-ins/Iterator/zipKeyed/basic-longest.js"));
it("basic-shortest.js", createTestHandler("built-ins/Iterator/zipKeyed/basic-shortest.js"));
it("basic-strict.js", createTestHandler("built-ins/Iterator/zipKeyed/basic-strict.js"));
it("is-function.js", createTestHandler("built-ins/Iterator/zipKeyed/is-function.js"));
it("iterables-containing-string-objects.js", createTestHandler("built-ins/Iterator/zipKeyed/iterables-containing-string-objects.js"));
it("iterables-iteration-after-reading-options.js", createTestHandler("built-ins/Iterator/zipKeyed/iterables-iteration-after-reading-options.js"));
it("iterables-iteration-deleted.js", createTestHandler("built-ins/Iterator/zipKeyed/iterables-iteration-deleted.js"));
it("iterables-iteration-enumerable.js", createTestHandler("built-ins/Iterator/zipKeyed/iterables-iteration-enumerable.js"));
it("iterables-iteration-get-abrupt-completion.js", createTestHandler("built-ins/Iterator/zipKeyed/iterables-iteration-get-abrupt-completion.js"));
it("iterables-iteration-get-iterator-flattenable-abrupt-completion.js", createTestHandler("built-ins/Iterator/zipKeyed/iterables-iteration-get-iterator-flattenable-abrupt-completion.js"));
it("iterables-iteration-get-own-property-abrupt-completion.js", createTestHandler("built-ins/Iterator/zipKeyed/iterables-iteration-get-own-property-abrupt-completion.js"));
it("iterables-iteration-inherited.js", createTestHandler("built-ins/Iterator/zipKeyed/iterables-iteration-inherited.js"));
it("iterables-iteration-symbol-key.js", createTestHandler("built-ins/Iterator/zipKeyed/iterables-iteration-symbol-key.js"));
it("iterables-iteration-undefined.js", createTestHandler("built-ins/Iterator/zipKeyed/iterables-iteration-undefined.js"));
it("iterables-iteration.js", createTestHandler("built-ins/Iterator/zipKeyed/iterables-iteration.js"));
it("iterables-primitive.js", createTestHandler("built-ins/Iterator/zipKeyed/iterables-primitive.js"));
it("iterator-zip-iteration-iterator-close-abrupt-completion.js", createTestHandler("built-ins/Iterator/zipKeyed/iterator-zip-iteration-iterator-close-abrupt-completion.js"));
it("iterator-zip-iteration-iterator-step-value-abrupt-completion.js", createTestHandler("built-ins/Iterator/zipKeyed/iterator-zip-iteration-iterator-step-value-abrupt-completion.js"));
it("iterator-zip-iteration-longest-iterator-close-abrupt-completion.js", createTestHandler("built-ins/Iterator/zipKeyed/iterator-zip-iteration-longest-iterator-close-abrupt-completion.js"));
it("iterator-zip-iteration-shortest-iterator-close-abrupt-completion.js", createTestHandler("built-ins/Iterator/zipKeyed/iterator-zip-iteration-shortest-iterator-close-abrupt-completion.js"));
it("iterator-zip-iteration-strict-iterator-close-i-is-not-zero-abrupt-completion.js", createTestHandler("built-ins/Iterator/zipKeyed/iterator-zip-iteration-strict-iterator-close-i-is-not-zero-abrupt-completion.js"));
it("iterator-zip-iteration-strict-iterator-close-i-is-zero-abrupt-completion.js", createTestHandler("built-ins/Iterator/zipKeyed/iterator-zip-iteration-strict-iterator-close-i-is-zero-abrupt-completion.js"));
it("iterator-zip-iteration-strict-iterator-step-abrupt-completion.js", createTestHandler("built-ins/Iterator/zipKeyed/iterator-zip-iteration-strict-iterator-step-abrupt-completion.js"));
it("iterator-zip-iteration.js", createTestHandler("built-ins/Iterator/zipKeyed/iterator-zip-iteration.js"));
it("length.js", createTestHandler("built-ins/Iterator/zipKeyed/length.js"));
it("name.js", createTestHandler("built-ins/Iterator/zipKeyed/name.js"));
it("non-constructible.js", createTestHandler("built-ins/Iterator/zipKeyed/non-constructible.js"));
it("options-mode.js", createTestHandler("built-ins/Iterator/zipKeyed/options-mode.js"));
it("options-padding.js", createTestHandler("built-ins/Iterator/zipKeyed/options-padding.js"));
it("options.js", createTestHandler("built-ins/Iterator/zipKeyed/options.js"));
it("padding-iteration-get-abrupt-completion.js", createTestHandler("built-ins/Iterator/zipKeyed/padding-iteration-get-abrupt-completion.js"));
it("padding-iteration.js", createTestHandler("built-ins/Iterator/zipKeyed/padding-iteration.js"));
it("prop-desc.js", createTestHandler("built-ins/Iterator/zipKeyed/prop-desc.js"));
it("proto.js", createTestHandler("built-ins/Iterator/zipKeyed/proto.js"));
it("result-is-iterator.js", createTestHandler("built-ins/Iterator/zipKeyed/result-is-iterator.js"));
it("results-object-from-array.js", createTestHandler("built-ins/Iterator/zipKeyed/results-object-from-array.js"));
it("results-object-has-default-attributes.js", createTestHandler("built-ins/Iterator/zipKeyed/results-object-has-default-attributes.js"));
it("results-object-has-no-undefined-iterables-properties.js", createTestHandler("built-ins/Iterator/zipKeyed/results-object-has-no-undefined-iterables-properties.js"));
it("suspended-start-iterator-close-calls-next.js", createTestHandler("built-ins/Iterator/zipKeyed/suspended-start-iterator-close-calls-next.js"));
it("suspended-start-iterator-close-calls-return.js", createTestHandler("built-ins/Iterator/zipKeyed/suspended-start-iterator-close-calls-return.js"));
it("suspended-yield-iterator-close-calls-next.js", createTestHandler("built-ins/Iterator/zipKeyed/suspended-yield-iterator-close-calls-next.js"));
it("suspended-yield-iterator-close-calls-return.js", createTestHandler("built-ins/Iterator/zipKeyed/suspended-yield-iterator-close-calls-return.js"));
});
