import { it, describe } from "vitest";
import { createTestHandler } from "../../../create-test-handler.js";

describe("construct", () => {
it("arguments-realm.js", createTestHandler("built-ins/Proxy/construct/arguments-realm.js"));
it("call-parameters-new-target.js", createTestHandler("built-ins/Proxy/construct/call-parameters-new-target.js"));
it("call-parameters.js", createTestHandler("built-ins/Proxy/construct/call-parameters.js"));
it("call-result.js", createTestHandler("built-ins/Proxy/construct/call-result.js"));
it("null-handler-realm.js", createTestHandler("built-ins/Proxy/construct/null-handler-realm.js"));
it("null-handler.js", createTestHandler("built-ins/Proxy/construct/null-handler.js"));
it("return-is-abrupt.js", createTestHandler("built-ins/Proxy/construct/return-is-abrupt.js"));
it("return-not-object-throws-boolean-realm.js", createTestHandler("built-ins/Proxy/construct/return-not-object-throws-boolean-realm.js"));
it("return-not-object-throws-boolean.js", createTestHandler("built-ins/Proxy/construct/return-not-object-throws-boolean.js"));
it("return-not-object-throws-null-realm.js", createTestHandler("built-ins/Proxy/construct/return-not-object-throws-null-realm.js"));
it("return-not-object-throws-null.js", createTestHandler("built-ins/Proxy/construct/return-not-object-throws-null.js"));
it("return-not-object-throws-number-realm.js", createTestHandler("built-ins/Proxy/construct/return-not-object-throws-number-realm.js"));
it("return-not-object-throws-number.js", createTestHandler("built-ins/Proxy/construct/return-not-object-throws-number.js"));
it("return-not-object-throws-string-realm.js", createTestHandler("built-ins/Proxy/construct/return-not-object-throws-string-realm.js"));
it("return-not-object-throws-string.js", createTestHandler("built-ins/Proxy/construct/return-not-object-throws-string.js"));
it("return-not-object-throws-symbol-realm.js", createTestHandler("built-ins/Proxy/construct/return-not-object-throws-symbol-realm.js"));
it("return-not-object-throws-symbol.js", createTestHandler("built-ins/Proxy/construct/return-not-object-throws-symbol.js"));
it("return-not-object-throws-undefined-realm.js", createTestHandler("built-ins/Proxy/construct/return-not-object-throws-undefined-realm.js"));
it("return-not-object-throws-undefined.js", createTestHandler("built-ins/Proxy/construct/return-not-object-throws-undefined.js"));
it("trap-is-missing-target-is-proxy.js", createTestHandler("built-ins/Proxy/construct/trap-is-missing-target-is-proxy.js"));
it("trap-is-not-callable-realm.js", createTestHandler("built-ins/Proxy/construct/trap-is-not-callable-realm.js"));
it("trap-is-not-callable.js", createTestHandler("built-ins/Proxy/construct/trap-is-not-callable.js"));
it("trap-is-null-target-is-proxy.js", createTestHandler("built-ins/Proxy/construct/trap-is-null-target-is-proxy.js"));
it("trap-is-null.js", createTestHandler("built-ins/Proxy/construct/trap-is-null.js"));
it("trap-is-undefined-no-property.js", createTestHandler("built-ins/Proxy/construct/trap-is-undefined-no-property.js"));
it("trap-is-undefined-proto-from-cross-realm-newtarget.js", createTestHandler("built-ins/Proxy/construct/trap-is-undefined-proto-from-cross-realm-newtarget.js"));
it("trap-is-undefined-proto-from-newtarget-realm.js", createTestHandler("built-ins/Proxy/construct/trap-is-undefined-proto-from-newtarget-realm.js"));
it("trap-is-undefined-target-is-proxy.js", createTestHandler("built-ins/Proxy/construct/trap-is-undefined-target-is-proxy.js"));
it("trap-is-undefined.js", createTestHandler("built-ins/Proxy/construct/trap-is-undefined.js"));
});
