import { it, describe } from "vitest";
import { createTestHandler } from "../../../create-test-handler.js";

describe("set", () => {
it("boolean-trap-result-is-false-boolean-return-false.js", createTestHandler("built-ins/Proxy/set/boolean-trap-result-is-false-boolean-return-false.js"));
it("boolean-trap-result-is-false-null-return-false.js", createTestHandler("built-ins/Proxy/set/boolean-trap-result-is-false-null-return-false.js"));
it("boolean-trap-result-is-false-number-return-false.js", createTestHandler("built-ins/Proxy/set/boolean-trap-result-is-false-number-return-false.js"));
it("boolean-trap-result-is-false-string-return-false.js", createTestHandler("built-ins/Proxy/set/boolean-trap-result-is-false-string-return-false.js"));
it("boolean-trap-result-is-false-undefined-return-false.js", createTestHandler("built-ins/Proxy/set/boolean-trap-result-is-false-undefined-return-false.js"));
it("call-parameters-prototype-dunder-proto.js", createTestHandler("built-ins/Proxy/set/call-parameters-prototype-dunder-proto.js"));
it("call-parameters-prototype-index.js", createTestHandler("built-ins/Proxy/set/call-parameters-prototype-index.js"));
it("call-parameters-prototype.js", createTestHandler("built-ins/Proxy/set/call-parameters-prototype.js"));
it("call-parameters.js", createTestHandler("built-ins/Proxy/set/call-parameters.js"));
it("null-handler.js", createTestHandler("built-ins/Proxy/set/null-handler.js"));
it("return-is-abrupt.js", createTestHandler("built-ins/Proxy/set/return-is-abrupt.js"));
it("return-true-target-property-accessor-is-configurable-set-is-undefined.js", createTestHandler("built-ins/Proxy/set/return-true-target-property-accessor-is-configurable-set-is-undefined.js"));
it("return-true-target-property-accessor-is-not-configurable.js", createTestHandler("built-ins/Proxy/set/return-true-target-property-accessor-is-not-configurable.js"));
it("return-true-target-property-is-not-configurable.js", createTestHandler("built-ins/Proxy/set/return-true-target-property-is-not-configurable.js"));
it("return-true-target-property-is-not-writable.js", createTestHandler("built-ins/Proxy/set/return-true-target-property-is-not-writable.js"));
it("target-property-is-accessor-not-configurable-set-is-undefined.js", createTestHandler("built-ins/Proxy/set/target-property-is-accessor-not-configurable-set-is-undefined.js"));
it("target-property-is-not-configurable-not-writable-not-equal-to-v.js", createTestHandler("built-ins/Proxy/set/target-property-is-not-configurable-not-writable-not-equal-to-v.js"));
it("trap-is-missing-receiver-multiple-calls-index.js", createTestHandler("built-ins/Proxy/set/trap-is-missing-receiver-multiple-calls-index.js"));
it("trap-is-missing-receiver-multiple-calls.js", createTestHandler("built-ins/Proxy/set/trap-is-missing-receiver-multiple-calls.js"));
it("trap-is-missing-target-is-proxy.js", createTestHandler("built-ins/Proxy/set/trap-is-missing-target-is-proxy.js"));
it("trap-is-not-callable-realm.js", createTestHandler("built-ins/Proxy/set/trap-is-not-callable-realm.js"));
it("trap-is-not-callable.js", createTestHandler("built-ins/Proxy/set/trap-is-not-callable.js"));
it("trap-is-null-receiver.js", createTestHandler("built-ins/Proxy/set/trap-is-null-receiver.js"));
it("trap-is-null-target-is-proxy.js", createTestHandler("built-ins/Proxy/set/trap-is-null-target-is-proxy.js"));
it("trap-is-undefined-no-property.js", createTestHandler("built-ins/Proxy/set/trap-is-undefined-no-property.js"));
it("trap-is-undefined-target-is-proxy.js", createTestHandler("built-ins/Proxy/set/trap-is-undefined-target-is-proxy.js"));
it("trap-is-undefined.js", createTestHandler("built-ins/Proxy/set/trap-is-undefined.js"));
});
