import { it, describe } from "vitest";
import { createTestHandler } from "../../../create-test-handler.js";

describe("prototype", () => {
describe("Symbol.iterator", () => {
it("not-a-constructor.js", createTestHandler("built-ins/Map/prototype/Symbol.iterator/not-a-constructor.js"));
});
it("Symbol.iterator.js", createTestHandler("built-ins/Map/prototype/Symbol.iterator.js"));
it("Symbol.toStringTag.js", createTestHandler("built-ins/Map/prototype/Symbol.toStringTag.js"));
describe("clear", () => {
it("clear-map.js", createTestHandler("built-ins/Map/prototype/clear/clear-map.js"));
it("clear.js", createTestHandler("built-ins/Map/prototype/clear/clear.js"));
it("context-is-not-map-object.js", createTestHandler("built-ins/Map/prototype/clear/context-is-not-map-object.js"));
it("context-is-not-object.js", createTestHandler("built-ins/Map/prototype/clear/context-is-not-object.js"));
it("context-is-set-object-throws.js", createTestHandler("built-ins/Map/prototype/clear/context-is-set-object-throws.js"));
it("context-is-weakmap-object-throws.js", createTestHandler("built-ins/Map/prototype/clear/context-is-weakmap-object-throws.js"));
it("length.js", createTestHandler("built-ins/Map/prototype/clear/length.js"));
it("map-data-list-is-preserved.js", createTestHandler("built-ins/Map/prototype/clear/map-data-list-is-preserved.js"));
it("name.js", createTestHandler("built-ins/Map/prototype/clear/name.js"));
it("not-a-constructor.js", createTestHandler("built-ins/Map/prototype/clear/not-a-constructor.js"));
it("returns-undefined.js", createTestHandler("built-ins/Map/prototype/clear/returns-undefined.js"));
});
it("constructor.js", createTestHandler("built-ins/Map/prototype/constructor.js"));
describe("delete", () => {
it("context-is-not-map-object.js", createTestHandler("built-ins/Map/prototype/delete/context-is-not-map-object.js"));
it("context-is-not-object.js", createTestHandler("built-ins/Map/prototype/delete/context-is-not-object.js"));
it("context-is-set-object-throws.js", createTestHandler("built-ins/Map/prototype/delete/context-is-set-object-throws.js"));
it("context-is-weakmap-object-throws.js", createTestHandler("built-ins/Map/prototype/delete/context-is-weakmap-object-throws.js"));
it("delete.js", createTestHandler("built-ins/Map/prototype/delete/delete.js"));
it("does-not-break-iterators.js", createTestHandler("built-ins/Map/prototype/delete/does-not-break-iterators.js"));
it("length.js", createTestHandler("built-ins/Map/prototype/delete/length.js"));
it("name.js", createTestHandler("built-ins/Map/prototype/delete/name.js"));
it("not-a-constructor.js", createTestHandler("built-ins/Map/prototype/delete/not-a-constructor.js"));
it("returns-false.js", createTestHandler("built-ins/Map/prototype/delete/returns-false.js"));
it("returns-true-for-deleted-entry.js", createTestHandler("built-ins/Map/prototype/delete/returns-true-for-deleted-entry.js"));
});
it("descriptor.js", createTestHandler("built-ins/Map/prototype/descriptor.js"));
describe("entries", () => {
it("does-not-have-mapdata-internal-slot-set.js", createTestHandler("built-ins/Map/prototype/entries/does-not-have-mapdata-internal-slot-set.js"));
it("does-not-have-mapdata-internal-slot-weakmap.js", createTestHandler("built-ins/Map/prototype/entries/does-not-have-mapdata-internal-slot-weakmap.js"));
it("does-not-have-mapdata-internal-slot.js", createTestHandler("built-ins/Map/prototype/entries/does-not-have-mapdata-internal-slot.js"));
it("entries.js", createTestHandler("built-ins/Map/prototype/entries/entries.js"));
it("length.js", createTestHandler("built-ins/Map/prototype/entries/length.js"));
it("name.js", createTestHandler("built-ins/Map/prototype/entries/name.js"));
it("not-a-constructor.js", createTestHandler("built-ins/Map/prototype/entries/not-a-constructor.js"));
it("returns-iterator-empty.js", createTestHandler("built-ins/Map/prototype/entries/returns-iterator-empty.js"));
it("returns-iterator.js", createTestHandler("built-ins/Map/prototype/entries/returns-iterator.js"));
it("this-not-object-throw.js", createTestHandler("built-ins/Map/prototype/entries/this-not-object-throw.js"));
});
describe("forEach", () => {
it("callback-parameters.js", createTestHandler("built-ins/Map/prototype/forEach/callback-parameters.js"));
it("callback-result-is-abrupt.js", createTestHandler("built-ins/Map/prototype/forEach/callback-result-is-abrupt.js"));
it("callback-this-non-strict.js", createTestHandler("built-ins/Map/prototype/forEach/callback-this-non-strict.js"));
it("callback-this-strict.js", createTestHandler("built-ins/Map/prototype/forEach/callback-this-strict.js"));
it("deleted-values-during-foreach.js", createTestHandler("built-ins/Map/prototype/forEach/deleted-values-during-foreach.js"));
it("does-not-have-mapdata-internal-slot-set.js", createTestHandler("built-ins/Map/prototype/forEach/does-not-have-mapdata-internal-slot-set.js"));
it("does-not-have-mapdata-internal-slot-weakmap.js", createTestHandler("built-ins/Map/prototype/forEach/does-not-have-mapdata-internal-slot-weakmap.js"));
it("does-not-have-mapdata-internal-slot.js", createTestHandler("built-ins/Map/prototype/forEach/does-not-have-mapdata-internal-slot.js"));
it("first-argument-is-not-callable.js", createTestHandler("built-ins/Map/prototype/forEach/first-argument-is-not-callable.js"));
it("forEach.js", createTestHandler("built-ins/Map/prototype/forEach/forEach.js"));
it("iterates-in-key-insertion-order.js", createTestHandler("built-ins/Map/prototype/forEach/iterates-in-key-insertion-order.js"));
it("iterates-values-added-after-foreach-begins.js", createTestHandler("built-ins/Map/prototype/forEach/iterates-values-added-after-foreach-begins.js"));
it("iterates-values-deleted-then-readded.js", createTestHandler("built-ins/Map/prototype/forEach/iterates-values-deleted-then-readded.js"));
it("length.js", createTestHandler("built-ins/Map/prototype/forEach/length.js"));
it("name.js", createTestHandler("built-ins/Map/prototype/forEach/name.js"));
it("not-a-constructor.js", createTestHandler("built-ins/Map/prototype/forEach/not-a-constructor.js"));
it("return-undefined.js", createTestHandler("built-ins/Map/prototype/forEach/return-undefined.js"));
it("second-parameter-as-callback-context.js", createTestHandler("built-ins/Map/prototype/forEach/second-parameter-as-callback-context.js"));
it("this-not-object-throw.js", createTestHandler("built-ins/Map/prototype/forEach/this-not-object-throw.js"));
});
describe("get", () => {
it("does-not-have-mapdata-internal-slot-set.js", createTestHandler("built-ins/Map/prototype/get/does-not-have-mapdata-internal-slot-set.js"));
it("does-not-have-mapdata-internal-slot-weakmap.js", createTestHandler("built-ins/Map/prototype/get/does-not-have-mapdata-internal-slot-weakmap.js"));
it("does-not-have-mapdata-internal-slot.js", createTestHandler("built-ins/Map/prototype/get/does-not-have-mapdata-internal-slot.js"));
it("get.js", createTestHandler("built-ins/Map/prototype/get/get.js"));
it("length.js", createTestHandler("built-ins/Map/prototype/get/length.js"));
it("name.js", createTestHandler("built-ins/Map/prototype/get/name.js"));
it("not-a-constructor.js", createTestHandler("built-ins/Map/prototype/get/not-a-constructor.js"));
it("returns-undefined.js", createTestHandler("built-ins/Map/prototype/get/returns-undefined.js"));
it("returns-value-different-key-types.js", createTestHandler("built-ins/Map/prototype/get/returns-value-different-key-types.js"));
it("returns-value-normalized-zero-key.js", createTestHandler("built-ins/Map/prototype/get/returns-value-normalized-zero-key.js"));
it("this-not-object-throw.js", createTestHandler("built-ins/Map/prototype/get/this-not-object-throw.js"));
});
describe("getOrInsert", () => {
it("append-new-values-normalizes-zero-key.js", createTestHandler("built-ins/Map/prototype/getOrInsert/append-new-values-normalizes-zero-key.js"));
it("append-new-values.js", createTestHandler("built-ins/Map/prototype/getOrInsert/append-new-values.js"));
it("append-value-if-key-is-not-present-different-key-types.js", createTestHandler("built-ins/Map/prototype/getOrInsert/append-value-if-key-is-not-present-different-key-types.js"));
it("does-not-have-mapdata-internal-slot-set.js", createTestHandler("built-ins/Map/prototype/getOrInsert/does-not-have-mapdata-internal-slot-set.js"));
it("does-not-have-mapdata-internal-slot-weakmap.js", createTestHandler("built-ins/Map/prototype/getOrInsert/does-not-have-mapdata-internal-slot-weakmap.js"));
it("does-not-have-mapdata-internal-slot.js", createTestHandler("built-ins/Map/prototype/getOrInsert/does-not-have-mapdata-internal-slot.js"));
it("getOrInsert.js", createTestHandler("built-ins/Map/prototype/getOrInsert/getOrInsert.js"));
it("length.js", createTestHandler("built-ins/Map/prototype/getOrInsert/length.js"));
it("name.js", createTestHandler("built-ins/Map/prototype/getOrInsert/name.js"));
it("not-a-constructor.js", createTestHandler("built-ins/Map/prototype/getOrInsert/not-a-constructor.js"));
it("returns-value-if-key-is-not-present-different-key-types.js", createTestHandler("built-ins/Map/prototype/getOrInsert/returns-value-if-key-is-not-present-different-key-types.js"));
it("returns-value-if-key-is-present-different-key-types.js", createTestHandler("built-ins/Map/prototype/getOrInsert/returns-value-if-key-is-present-different-key-types.js"));
it("returns-value-normalized-zero-key.js", createTestHandler("built-ins/Map/prototype/getOrInsert/returns-value-normalized-zero-key.js"));
it("this-not-object-throw.js", createTestHandler("built-ins/Map/prototype/getOrInsert/this-not-object-throw.js"));
});
describe("getOrInsertComputed", () => {
it("append-new-values-normalizes-zero-key.js", createTestHandler("built-ins/Map/prototype/getOrInsertComputed/append-new-values-normalizes-zero-key.js"));
it("append-new-values.js", createTestHandler("built-ins/Map/prototype/getOrInsertComputed/append-new-values.js"));
it("append-value-if-key-is-not-present-different-key-types.js", createTestHandler("built-ins/Map/prototype/getOrInsertComputed/append-value-if-key-is-not-present-different-key-types.js"));
it("callbackfn-throws.js", createTestHandler("built-ins/Map/prototype/getOrInsertComputed/callbackfn-throws.js"));
it("canonical-key-passed-to-callback.js", createTestHandler("built-ins/Map/prototype/getOrInsertComputed/canonical-key-passed-to-callback.js"));
it("check-callback-fn-args.js", createTestHandler("built-ins/Map/prototype/getOrInsertComputed/check-callback-fn-args.js"));
it("check-state-after-callback-fn-throws.js", createTestHandler("built-ins/Map/prototype/getOrInsertComputed/check-state-after-callback-fn-throws.js"));
it("different-types-function-callbackfn-does-not-throw.js", createTestHandler("built-ins/Map/prototype/getOrInsertComputed/different-types-function-callbackfn-does-not-throw.js"));
it("does-not-evaluate-callbackfn-if-key-present.js", createTestHandler("built-ins/Map/prototype/getOrInsertComputed/does-not-evaluate-callbackfn-if-key-present.js"));
it("does-not-have-mapdata-internal-slot-set.js", createTestHandler("built-ins/Map/prototype/getOrInsertComputed/does-not-have-mapdata-internal-slot-set.js"));
it("does-not-have-mapdata-internal-slot-weakmap.js", createTestHandler("built-ins/Map/prototype/getOrInsertComputed/does-not-have-mapdata-internal-slot-weakmap.js"));
it("getOrInsertComputed.js", createTestHandler("built-ins/Map/prototype/getOrInsertComputed/getOrInsertComputed.js"));
it("not-a-constructor.js", createTestHandler("built-ins/Map/prototype/getOrInsertComputed/not-a-constructor.js"));
it("not-a-function-callbackfn-throws.js", createTestHandler("built-ins/Map/prototype/getOrInsertComputed/not-a-function-callbackfn-throws.js"));
it("overwrites-mutation-from-callbackfn.js", createTestHandler("built-ins/Map/prototype/getOrInsertComputed/overwrites-mutation-from-callbackfn.js"));
it("returns-value-if-key-is-not-present-different-key-types.js", createTestHandler("built-ins/Map/prototype/getOrInsertComputed/returns-value-if-key-is-not-present-different-key-types.js"));
it("returns-value-if-key-is-present-different-key-types.js", createTestHandler("built-ins/Map/prototype/getOrInsertComputed/returns-value-if-key-is-present-different-key-types.js"));
it("returns-value-normalized-zero-key.js", createTestHandler("built-ins/Map/prototype/getOrInsertComputed/returns-value-normalized-zero-key.js"));
it("this-not-object-throw.js", createTestHandler("built-ins/Map/prototype/getOrInsertComputed/this-not-object-throw.js"));
});
describe("has", () => {
it("does-not-have-mapdata-internal-slot-set.js", createTestHandler("built-ins/Map/prototype/has/does-not-have-mapdata-internal-slot-set.js"));
it("does-not-have-mapdata-internal-slot-weakmap.js", createTestHandler("built-ins/Map/prototype/has/does-not-have-mapdata-internal-slot-weakmap.js"));
it("does-not-have-mapdata-internal-slot.js", createTestHandler("built-ins/Map/prototype/has/does-not-have-mapdata-internal-slot.js"));
it("has.js", createTestHandler("built-ins/Map/prototype/has/has.js"));
it("length.js", createTestHandler("built-ins/Map/prototype/has/length.js"));
it("name.js", createTestHandler("built-ins/Map/prototype/has/name.js"));
it("normalizes-zero-key.js", createTestHandler("built-ins/Map/prototype/has/normalizes-zero-key.js"));
it("not-a-constructor.js", createTestHandler("built-ins/Map/prototype/has/not-a-constructor.js"));
it("return-false-different-key-types.js", createTestHandler("built-ins/Map/prototype/has/return-false-different-key-types.js"));
it("return-true-different-key-types.js", createTestHandler("built-ins/Map/prototype/has/return-true-different-key-types.js"));
it("this-not-object-throw.js", createTestHandler("built-ins/Map/prototype/has/this-not-object-throw.js"));
});
describe("keys", () => {
it("does-not-have-mapdata-internal-slot-set.js", createTestHandler("built-ins/Map/prototype/keys/does-not-have-mapdata-internal-slot-set.js"));
it("does-not-have-mapdata-internal-slot-weakmap.js", createTestHandler("built-ins/Map/prototype/keys/does-not-have-mapdata-internal-slot-weakmap.js"));
it("does-not-have-mapdata-internal-slot.js", createTestHandler("built-ins/Map/prototype/keys/does-not-have-mapdata-internal-slot.js"));
it("keys.js", createTestHandler("built-ins/Map/prototype/keys/keys.js"));
it("length.js", createTestHandler("built-ins/Map/prototype/keys/length.js"));
it("name.js", createTestHandler("built-ins/Map/prototype/keys/name.js"));
it("not-a-constructor.js", createTestHandler("built-ins/Map/prototype/keys/not-a-constructor.js"));
it("returns-iterator-empty.js", createTestHandler("built-ins/Map/prototype/keys/returns-iterator-empty.js"));
it("returns-iterator.js", createTestHandler("built-ins/Map/prototype/keys/returns-iterator.js"));
it("this-not-object-throw.js", createTestHandler("built-ins/Map/prototype/keys/this-not-object-throw.js"));
});
describe("set", () => {
it("append-new-values-normalizes-zero-key.js", createTestHandler("built-ins/Map/prototype/set/append-new-values-normalizes-zero-key.js"));
it("append-new-values-return-map.js", createTestHandler("built-ins/Map/prototype/set/append-new-values-return-map.js"));
it("append-new-values.js", createTestHandler("built-ins/Map/prototype/set/append-new-values.js"));
it("does-not-have-mapdata-internal-slot-set.js", createTestHandler("built-ins/Map/prototype/set/does-not-have-mapdata-internal-slot-set.js"));
it("does-not-have-mapdata-internal-slot-weakmap.js", createTestHandler("built-ins/Map/prototype/set/does-not-have-mapdata-internal-slot-weakmap.js"));
it("does-not-have-mapdata-internal-slot.js", createTestHandler("built-ins/Map/prototype/set/does-not-have-mapdata-internal-slot.js"));
it("length.js", createTestHandler("built-ins/Map/prototype/set/length.js"));
it("name.js", createTestHandler("built-ins/Map/prototype/set/name.js"));
it("not-a-constructor.js", createTestHandler("built-ins/Map/prototype/set/not-a-constructor.js"));
it("replaces-a-value-normalizes-zero-key.js", createTestHandler("built-ins/Map/prototype/set/replaces-a-value-normalizes-zero-key.js"));
it("replaces-a-value-returns-map.js", createTestHandler("built-ins/Map/prototype/set/replaces-a-value-returns-map.js"));
it("replaces-a-value.js", createTestHandler("built-ins/Map/prototype/set/replaces-a-value.js"));
it("set.js", createTestHandler("built-ins/Map/prototype/set/set.js"));
it("this-not-object-throw.js", createTestHandler("built-ins/Map/prototype/set/this-not-object-throw.js"));
});
describe("size", () => {
it("does-not-have-mapdata-internal-slot-set.js", createTestHandler("built-ins/Map/prototype/size/does-not-have-mapdata-internal-slot-set.js"));
it("does-not-have-mapdata-internal-slot-weakmap.js", createTestHandler("built-ins/Map/prototype/size/does-not-have-mapdata-internal-slot-weakmap.js"));
it("does-not-have-mapdata-internal-slot.js", createTestHandler("built-ins/Map/prototype/size/does-not-have-mapdata-internal-slot.js"));
it("length.js", createTestHandler("built-ins/Map/prototype/size/length.js"));
it("name.js", createTestHandler("built-ins/Map/prototype/size/name.js"));
it("returns-count-of-present-values-before-after-set-clear.js", createTestHandler("built-ins/Map/prototype/size/returns-count-of-present-values-before-after-set-clear.js"));
it("returns-count-of-present-values-before-after-set-delete.js", createTestHandler("built-ins/Map/prototype/size/returns-count-of-present-values-before-after-set-delete.js"));
it("returns-count-of-present-values-by-insertion.js", createTestHandler("built-ins/Map/prototype/size/returns-count-of-present-values-by-insertion.js"));
it("returns-count-of-present-values-by-iterable.js", createTestHandler("built-ins/Map/prototype/size/returns-count-of-present-values-by-iterable.js"));
it("size.js", createTestHandler("built-ins/Map/prototype/size/size.js"));
it("this-not-object-throw.js", createTestHandler("built-ins/Map/prototype/size/this-not-object-throw.js"));
});
describe("values", () => {
it("does-not-have-mapdata-internal-slot-set.js", createTestHandler("built-ins/Map/prototype/values/does-not-have-mapdata-internal-slot-set.js"));
it("does-not-have-mapdata-internal-slot-weakmap.js", createTestHandler("built-ins/Map/prototype/values/does-not-have-mapdata-internal-slot-weakmap.js"));
it("does-not-have-mapdata-internal-slot.js", createTestHandler("built-ins/Map/prototype/values/does-not-have-mapdata-internal-slot.js"));
it("length.js", createTestHandler("built-ins/Map/prototype/values/length.js"));
it("name.js", createTestHandler("built-ins/Map/prototype/values/name.js"));
it("not-a-constructor.js", createTestHandler("built-ins/Map/prototype/values/not-a-constructor.js"));
it("returns-iterator-empty.js", createTestHandler("built-ins/Map/prototype/values/returns-iterator-empty.js"));
it("returns-iterator.js", createTestHandler("built-ins/Map/prototype/values/returns-iterator.js"));
it("this-not-object-throw.js", createTestHandler("built-ins/Map/prototype/values/this-not-object-throw.js"));
it("values.js", createTestHandler("built-ins/Map/prototype/values/values.js"));
});
});
