import { it, describe } from "vitest";
import { createTestHandler } from "../../../create-test-handler.js";

describe("named-groups", () => {
it("duplicate-names-exec.js", createTestHandler("built-ins/RegExp/named-groups/duplicate-names-exec.js"));
it("duplicate-names-group-property-enumeration-order.js", createTestHandler("built-ins/RegExp/named-groups/duplicate-names-group-property-enumeration-order.js"));
it("duplicate-names-match-indices.js", createTestHandler("built-ins/RegExp/named-groups/duplicate-names-match-indices.js"));
it("duplicate-names-match.js", createTestHandler("built-ins/RegExp/named-groups/duplicate-names-match.js"));
it("duplicate-names-matchall.js", createTestHandler("built-ins/RegExp/named-groups/duplicate-names-matchall.js"));
it("duplicate-names-replace.js", createTestHandler("built-ins/RegExp/named-groups/duplicate-names-replace.js"));
it("duplicate-names-replaceall.js", createTestHandler("built-ins/RegExp/named-groups/duplicate-names-replaceall.js"));
it("duplicate-names-search.js", createTestHandler("built-ins/RegExp/named-groups/duplicate-names-search.js"));
it("duplicate-names-split.js", createTestHandler("built-ins/RegExp/named-groups/duplicate-names-split.js"));
it("duplicate-names-test.js", createTestHandler("built-ins/RegExp/named-groups/duplicate-names-test.js"));
it("functional-replace-global.js", createTestHandler("built-ins/RegExp/named-groups/functional-replace-global.js"));
it("functional-replace-non-global.js", createTestHandler("built-ins/RegExp/named-groups/functional-replace-non-global.js"));
it("groups-object-subclass-sans.js", createTestHandler("built-ins/RegExp/named-groups/groups-object-subclass-sans.js"));
it("groups-object-subclass.js", createTestHandler("built-ins/RegExp/named-groups/groups-object-subclass.js"));
it("groups-object-undefined.js", createTestHandler("built-ins/RegExp/named-groups/groups-object-undefined.js"));
it("groups-object-unmatched.js", createTestHandler("built-ins/RegExp/named-groups/groups-object-unmatched.js"));
it("groups-object.js", createTestHandler("built-ins/RegExp/named-groups/groups-object.js"));
it("groups-properties.js", createTestHandler("built-ins/RegExp/named-groups/groups-properties.js"));
it("lookbehind.js", createTestHandler("built-ins/RegExp/named-groups/lookbehind.js"));
it("non-unicode-match.js", createTestHandler("built-ins/RegExp/named-groups/non-unicode-match.js"));
it("non-unicode-property-names-invalid.js", createTestHandler("built-ins/RegExp/named-groups/non-unicode-property-names-invalid.js"));
it("non-unicode-property-names-valid.js", createTestHandler("built-ins/RegExp/named-groups/non-unicode-property-names-valid.js"));
it("non-unicode-property-names.js", createTestHandler("built-ins/RegExp/named-groups/non-unicode-property-names.js"));
it("non-unicode-references.js", createTestHandler("built-ins/RegExp/named-groups/non-unicode-references.js"));
it("string-replace-escaped.js", createTestHandler("built-ins/RegExp/named-groups/string-replace-escaped.js"));
it("string-replace-get.js", createTestHandler("built-ins/RegExp/named-groups/string-replace-get.js"));
it("string-replace-missing.js", createTestHandler("built-ins/RegExp/named-groups/string-replace-missing.js"));
it("string-replace-nocaptures.js", createTestHandler("built-ins/RegExp/named-groups/string-replace-nocaptures.js"));
it("string-replace-numbered.js", createTestHandler("built-ins/RegExp/named-groups/string-replace-numbered.js"));
it("string-replace-unclosed.js", createTestHandler("built-ins/RegExp/named-groups/string-replace-unclosed.js"));
it("string-replace-undefined.js", createTestHandler("built-ins/RegExp/named-groups/string-replace-undefined.js"));
it("unicode-match.js", createTestHandler("built-ins/RegExp/named-groups/unicode-match.js"));
it("unicode-property-names-invalid.js", createTestHandler("built-ins/RegExp/named-groups/unicode-property-names-invalid.js"));
it("unicode-property-names-valid.js", createTestHandler("built-ins/RegExp/named-groups/unicode-property-names-valid.js"));
it("unicode-property-names.js", createTestHandler("built-ins/RegExp/named-groups/unicode-property-names.js"));
it("unicode-references.js", createTestHandler("built-ins/RegExp/named-groups/unicode-references.js"));
});
