import { it, describe } from "vitest";
import { createTestHandler } from "../../../create-test-handler.js";

describe("pow", () => {
it("applying-the-exp-operator_A1.js", createTestHandler("built-ins/Math/pow/applying-the-exp-operator_A1.js"));
it("applying-the-exp-operator_A10.js", createTestHandler("built-ins/Math/pow/applying-the-exp-operator_A10.js"));
it("applying-the-exp-operator_A11.js", createTestHandler("built-ins/Math/pow/applying-the-exp-operator_A11.js"));
it("applying-the-exp-operator_A12.js", createTestHandler("built-ins/Math/pow/applying-the-exp-operator_A12.js"));
it("applying-the-exp-operator_A13.js", createTestHandler("built-ins/Math/pow/applying-the-exp-operator_A13.js"));
it("applying-the-exp-operator_A14.js", createTestHandler("built-ins/Math/pow/applying-the-exp-operator_A14.js"));
it("applying-the-exp-operator_A15.js", createTestHandler("built-ins/Math/pow/applying-the-exp-operator_A15.js"));
it("applying-the-exp-operator_A16.js", createTestHandler("built-ins/Math/pow/applying-the-exp-operator_A16.js"));
it("applying-the-exp-operator_A17.js", createTestHandler("built-ins/Math/pow/applying-the-exp-operator_A17.js"));
it("applying-the-exp-operator_A18.js", createTestHandler("built-ins/Math/pow/applying-the-exp-operator_A18.js"));
it("applying-the-exp-operator_A19.js", createTestHandler("built-ins/Math/pow/applying-the-exp-operator_A19.js"));
it("applying-the-exp-operator_A2.js", createTestHandler("built-ins/Math/pow/applying-the-exp-operator_A2.js"));
it("applying-the-exp-operator_A20.js", createTestHandler("built-ins/Math/pow/applying-the-exp-operator_A20.js"));
it("applying-the-exp-operator_A21.js", createTestHandler("built-ins/Math/pow/applying-the-exp-operator_A21.js"));
it("applying-the-exp-operator_A22.js", createTestHandler("built-ins/Math/pow/applying-the-exp-operator_A22.js"));
it("applying-the-exp-operator_A23.js", createTestHandler("built-ins/Math/pow/applying-the-exp-operator_A23.js"));
it("applying-the-exp-operator_A3.js", createTestHandler("built-ins/Math/pow/applying-the-exp-operator_A3.js"));
it("applying-the-exp-operator_A4.js", createTestHandler("built-ins/Math/pow/applying-the-exp-operator_A4.js"));
it("applying-the-exp-operator_A5.js", createTestHandler("built-ins/Math/pow/applying-the-exp-operator_A5.js"));
it("applying-the-exp-operator_A6.js", createTestHandler("built-ins/Math/pow/applying-the-exp-operator_A6.js"));
it("applying-the-exp-operator_A7.js", createTestHandler("built-ins/Math/pow/applying-the-exp-operator_A7.js"));
it("applying-the-exp-operator_A8.js", createTestHandler("built-ins/Math/pow/applying-the-exp-operator_A8.js"));
it("applying-the-exp-operator_A9.js", createTestHandler("built-ins/Math/pow/applying-the-exp-operator_A9.js"));
it("int32_min-exponent.js", createTestHandler("built-ins/Math/pow/int32_min-exponent.js"));
it("length.js", createTestHandler("built-ins/Math/pow/length.js"));
it("name.js", createTestHandler("built-ins/Math/pow/name.js"));
it("not-a-constructor.js", createTestHandler("built-ins/Math/pow/not-a-constructor.js"));
it("prop-desc.js", createTestHandler("built-ins/Math/pow/prop-desc.js"));
});
