# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test262 Built-ins Regression Tests

on:
  workflow_call:
    inputs:
      ref:
        description: "Git ref (SHA, branch, or tag) to test against"
        required: true
        type: string

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          ref: ${{ inputs.ref }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v6
      - name: Use Node.js 24.6
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: "pnpm"
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Run Test262 builtins tests against baseline
        run: pnpm run --filter @suntime-js/core test:builtins:baseline --reporter=default --reporter=github-actions
