import { it, describe } from "vitest";
import { createTestHandler } from "../../../create-test-handler.js";

describe("from", () => {
it("Array.from-descriptor.js", createTestHandler("built-ins/Array/from/Array.from-descriptor.js"));
it("Array.from-name.js", createTestHandler("built-ins/Array/from/Array.from-name.js"));
it("Array.from_arity.js", createTestHandler("built-ins/Array/from/Array.from_arity.js"));
it("Array.from_forwards-length-for-array-likes.js", createTestHandler("built-ins/Array/from/Array.from_forwards-length-for-array-likes.js"));
it("array-like-has-length-but-no-indexes-with-values.js", createTestHandler("built-ins/Array/from/array-like-has-length-but-no-indexes-with-values.js"));
it("calling-from-valid-1-noStrict.js", createTestHandler("built-ins/Array/from/calling-from-valid-1-noStrict.js"));
it("calling-from-valid-1-onlyStrict.js", createTestHandler("built-ins/Array/from/calling-from-valid-1-onlyStrict.js"));
it("calling-from-valid-2.js", createTestHandler("built-ins/Array/from/calling-from-valid-2.js"));
it("elements-added-after.js", createTestHandler("built-ins/Array/from/elements-added-after.js"));
it("elements-deleted-after.js", createTestHandler("built-ins/Array/from/elements-deleted-after.js"));
it("elements-updated-after.js", createTestHandler("built-ins/Array/from/elements-updated-after.js"));
it("from-array.js", createTestHandler("built-ins/Array/from/from-array.js"));
it("from-string.js", createTestHandler("built-ins/Array/from/from-string.js"));
it("get-iter-method-err.js", createTestHandler("built-ins/Array/from/get-iter-method-err.js"));
it("items-is-arraybuffer.js", createTestHandler("built-ins/Array/from/items-is-arraybuffer.js"));
it("items-is-null-throws.js", createTestHandler("built-ins/Array/from/items-is-null-throws.js"));
it("iter-adv-err.js", createTestHandler("built-ins/Array/from/iter-adv-err.js"));
it("iter-cstm-ctor-err.js", createTestHandler("built-ins/Array/from/iter-cstm-ctor-err.js"));
it("iter-cstm-ctor.js", createTestHandler("built-ins/Array/from/iter-cstm-ctor.js"));
it("iter-get-iter-err.js", createTestHandler("built-ins/Array/from/iter-get-iter-err.js"));
it("iter-get-iter-val-err.js", createTestHandler("built-ins/Array/from/iter-get-iter-val-err.js"));
it("iter-map-fn-args.js", createTestHandler("built-ins/Array/from/iter-map-fn-args.js"));
it("iter-map-fn-err.js", createTestHandler("built-ins/Array/from/iter-map-fn-err.js"));
it("iter-map-fn-return.js", createTestHandler("built-ins/Array/from/iter-map-fn-return.js"));
it("iter-map-fn-this-arg.js", createTestHandler("built-ins/Array/from/iter-map-fn-this-arg.js"));
it("iter-map-fn-this-non-strict.js", createTestHandler("built-ins/Array/from/iter-map-fn-this-non-strict.js"));
it("iter-map-fn-this-strict.js", createTestHandler("built-ins/Array/from/iter-map-fn-this-strict.js"));
it("iter-set-elem-prop-err.js", createTestHandler("built-ins/Array/from/iter-set-elem-prop-err.js"));
it("iter-set-elem-prop-non-writable.js", createTestHandler("built-ins/Array/from/iter-set-elem-prop-non-writable.js"));
it("iter-set-elem-prop.js", createTestHandler("built-ins/Array/from/iter-set-elem-prop.js"));
it("iter-set-length-err.js", createTestHandler("built-ins/Array/from/iter-set-length-err.js"));
it("iter-set-length.js", createTestHandler("built-ins/Array/from/iter-set-length.js"));
it("mapfn-is-not-callable-typeerror.js", createTestHandler("built-ins/Array/from/mapfn-is-not-callable-typeerror.js"));
it("mapfn-is-symbol-throws.js", createTestHandler("built-ins/Array/from/mapfn-is-symbol-throws.js"));
it("mapfn-throws-exception.js", createTestHandler("built-ins/Array/from/mapfn-throws-exception.js"));
it("not-a-constructor.js", createTestHandler("built-ins/Array/from/not-a-constructor.js"));
it("proto-from-ctor-realm.js", createTestHandler("built-ins/Array/from/proto-from-ctor-realm.js"));
it("source-array-boundary.js", createTestHandler("built-ins/Array/from/source-array-boundary.js"));
it("source-object-constructor.js", createTestHandler("built-ins/Array/from/source-object-constructor.js"));
it("source-object-iterator-1.js", createTestHandler("built-ins/Array/from/source-object-iterator-1.js"));
it("source-object-iterator-2.js", createTestHandler("built-ins/Array/from/source-object-iterator-2.js"));
it("source-object-length-set-elem-prop-err.js", createTestHandler("built-ins/Array/from/source-object-length-set-elem-prop-err.js"));
it("source-object-length-set-elem-prop-non-writable.js", createTestHandler("built-ins/Array/from/source-object-length-set-elem-prop-non-writable.js"));
it("source-object-length.js", createTestHandler("built-ins/Array/from/source-object-length.js"));
it("source-object-missing.js", createTestHandler("built-ins/Array/from/source-object-missing.js"));
it("source-object-without.js", createTestHandler("built-ins/Array/from/source-object-without.js"));
it("this-null.js", createTestHandler("built-ins/Array/from/this-null.js"));
});
